Repository Azure/azure-cli-extensions, pull requests merged in 2018-04, with the labels that each got.

#135 Az Cli IoT extension v0.4.3
  src/index.json
Labels: extension/iot

#133 Update batch cli extension
  src/index.json
Labels: extension/batch

#108 Websites: Adding metadata to support the isPreview feature
  src/index.json
  src/webapp/azext_webapp/azext_metadata.json
  src/webapp/setup.py
Labels: extension/webapp
