Repository Azure/azure-cli-extensions, pull requests merged in 2020-03, with the labels that each got.

#1369 [CI] Remove travis related files
  .travis.yml
  scripts/avail-ext-doc/Dockerfile
  scripts/avail-ext-doc/README.md
  scripts/avail-ext-doc/list-template.md
  scripts/avail-ext-doc/main.py
  scripts/avail-ext-doc/requirements.txt
  scripts/ci/test_static.py
  scripts/ci/test_static.sh
Labels: CI

#1334 [CI] add prechek logic in job LintModifiedExtension
  .github/PULL_REQUEST_TEMPLATE.md
  azure-pipelines.yml
  scripts/ci/verify_linter.py
Labels: CI

#1387 [CI] Run linter on pull request only and remove unnecessary files
  azure-cli-extensions.pyproj
  azure-pipelines.yml
  scripts/ci/index_changes.py
  scripts/ci/verify_linter.py
  scripts/ci/verify_modified_index.sh
Labels: CI

#1392 [CI] fix wrong usage of subprocess.check_call() in Linter
  scripts/ci/verify_linter.py
Labels: CI

#1383 [AKS] aks update: Override outbound IPs with input values when update.
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_loadbalancer.py
  src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py
Labels: AKS

#1411 [AKS] publish uptime-sla
  src/aks-preview/HISTORY.md
  src/aks-preview/setup.py
Labels: AKS

#1345 [ai-examples] Switch to a new hook
  src/ai-examples/HISTORY.rst
  src/ai-examples/README.rst
  src/ai-examples/azext_ai_examples/__init__.py
  src/ai-examples/azext_ai_examples/azext_metadata.json
  src/ai-examples/azext_ai_examples/custom.py
  src/ai-examples/setup.py
Labels: do-not-merge

#1417 Add AAD V2 support to aks-preview
  src/aks-preview/HISTORY.md
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_helpers.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_managed_aad.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS

#1439 [CI] remove limit on wheel name
  scripts/ci/test_index.py
Labels: CI

#1448 [CI] add license checker
  azure-cli-extensions.pyproj
  azure-pipelines.yml
  scripts/ci/source_code_static_analysis.py
  scripts/ci/verify_license.py
  src/hack/azext_hack/_validators.py
  src/hack/azext_hack/_website_utils.py
  src/hack/azext_hack/custom.py
Labels: CI

#1430 adding --mode to nodepool command and update the 0301 sdk
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_format.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2020_03_01/models/_models_py3.py
Labels: AKS

#1405 enable kubenet for udr
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_helpers.py
Labels: AKS
