Repository Azure/azure-cli-extensions, pull requests merged in 2020-04, with the labels that each got.

#1470 [AKS] use latest api version for autoscaler profile validator
  src/aks-preview/azext_aks_preview/_validators.py
Labels: AKS

#1493 [CI] Overwrite AZURE_EXTENSION_DIR to fix bug that CI will fail if installing azure-devops extension
  azure-pipelines.yml
Labels: CI

#1451 Presentation aks fix: The name displayed for the storage is inreality everything before -hcp-, this fix helps clearing that confusion.
  src/aks-preview/azext_aks_preview/_helpers.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py
Labels: AKS

#1516 {Pipeline} print stacktrace when exception
  scripts/ci/index_ref_doc.py
Labels: do-not-merge

#1523 spring-cloud: add support to enable/disable MSI
  src/spring-cloud/azext_spring_cloud/_help.py
  src/spring-cloud/azext_spring_cloud/_params.py
  src/spring-cloud/azext_spring_cloud/commands.py
  src/spring-cloud/azext_spring_cloud/custom.py
  src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/__init__.py
  src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_app_platform_management_client_enums.py
  src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_models.py
  src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/models/_models_py3.py
  src/spring-cloud/azext_spring_cloud/vendored_sdks/appplatform/operations/_apps_operations.py
Labels: Spring Cloud

#1558 Update spring cloud deployment and app table output to align with Azure portal
  src/spring-cloud/azext_spring_cloud/_transformers.py
Labels: Spring Cloud

#1609 Add portal generated module init file
  src/portal/HISTORY.rst
  src/portal/azext_portal/generated/__init__.py
  src/portal/setup.py
Labels: bug

#1624 [CI] Add wheel preinstallation for job IndexRefDocVerify and fix azure-firewall test recordings
  azure-pipelines.yml
  src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_ip_config.yaml
  src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_management_ip_config.yaml
  src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_firewall_policy.yaml
Labels: CI

#1628 [CI] Remove wheel usage
  azure-pipelines.yml
  scripts/ci/util.py
Labels: CI
