Repository Azure/azure-cli-extensions, pull requests merged in 2020-01, with the labels that each got.

#1174 [CI] Move 2, 3: Copy job SourceTests, LintModifiedExtensions from Travis to ADO
  azure-pipelines.yml
  scripts/ci/test_source.py
Labels: CI

#1177 [Network][Feature]az network firewall create: support threat intel whitelist and private ranges
  src/azure-firewall/HISTORY.rst
  src/azure-firewall/azext_firewall/_help.py
  src/azure-firewall/azext_firewall/_params.py
  src/azure-firewall/azext_firewall/_validators.py
  src/azure-firewall/azext_firewall/commands.py
  src/azure-firewall/azext_firewall/custom.py
  src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_threat_intel_whitelist.yaml
  src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
  src/azure-firewall/setup.py
  src/index.json
Labels: Network, Network - Firewall

#1197 Chore: Disable job CredScan for ADO sceurity concern
  azure-pipelines.yml
Labels: CI

#1198 Test to fix CI job
  scripts/ci/test_source.py
Labels: do-not-merge

#1200 fix: CI job "SourceTests" will fail in non PR trigger build
  scripts/ci/test_source.py
Labels: CI

#1204 Release pipeline test
  azure-pipelines.yml
Labels: CI
