Repository Azure/azure-cli-extensions, pull requests merged in 2022-08, with the labels that each got.

#5174 [AKS] `az aks`: Add support for CBLMarinerV2
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_params.py
Labels: AKS, Auto-Assign

#5175 {CI} Update milestone from Jul 2022 (2022-08-02) to Aug 2022 (2022-09-06)
  .github/fabricbot.json
Labels: CI, Auto-Assign

#5181 `az portal dashboard`: `--input-path` should accept other encoding types besides UTF-8 encoding
  src/portal/HISTORY.rst
  src/portal/azext_portal/generated/custom.py
  src/portal/azext_portal/tests/latest/properties-update.json
  src/portal/azext_portal/tests/latest/recordings/test_portal.yaml
  src/portal/azext_portal/tests/latest/test_portal_scenario.py
  src/portal/setup.py
Labels: Portal

#5183 {CI} Fix Azure CLI Extensions Sync to MicrosoftDocs error
  scripts/ci/avail-ext-doc/requirements.txt
Labels: CI, Auto-Assign

#5197 {CI} Test auto merge
  text.txt
Labels: CI, Auto-Assign

#5205 {CI} test auto commit
  text.txt
Labels: CI, Auto-Assign

#5206 {CI} Test auto merge
  text.txt
Labels: CI, Auto-Assign

#5207 {CI} Test auto merge
  text.txt
Labels: CI, Auto-Assign

#5203 [serial-console] Add support for managed boot diagnostics storage account
  src/serial-console/HISTORY.rst
  src/serial-console/azext_serialconsole/_help.py
  src/serial-console/azext_serialconsole/custom.py
  src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VM.yaml
  src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VMSS.yaml
  src/serial-console/azext_serialconsole/tests/latest/recordings/test_enable_disable.yaml
  src/serial-console/azext_serialconsole/tests/latest/test_serialconsole_scenario.py
  src/serial-console/setup.py
Labels: Auto-Assign

#5211 [AzureFirewall] Update help message
  src/azure-firewall/azext_firewall/_help.py
Labels: Network, Auto-Assign

#5204 [k8s-extension] Update extension CLI to v1.3.0
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/_params.py
  src/k8s-extension/azext_k8s_extension/consts.py
  src/k8s-extension/azext_k8s_extension/custom.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/AzureDefender.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/DefaultExtension.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/OpenServiceMesh.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/PartnerExtensionModel.py
  src/k8s-extension/azext_k8s_extension/utils.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#5218 {CI} drop python 3.6
  azure-pipelines.yml
Labels: CI, Auto-Assign

#5222 chore(arcdata): version bump to 1.4.5
  src/index.json
Labels: Auto-Assign

#5213 [AzureFirewall] `az network firewall`: Add parameter `--fat-flow-logging`
  src/azure-firewall/HISTORY.rst
  src/azure-firewall/azext_firewall/_params.py
  src/azure-firewall/azext_firewall/custom.py
  src/azure-firewall/azext_firewall/tests/latest/recordings/test_azure_firewall_with_v2.yaml
  src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
  src/azure-firewall/setup.py
Labels: Network, Auto-Assign

#5214 {aks-preview} Fix #17699: Update resource group name to generic text …
  src/aks-preview/azext_aks_preview/_help.py
Labels: AKS, Auto-Assign

#5219 {AKS} Fix #23468: `az aks nodepool wait` crashes with error "'Namespace' object has no attribute 'nodepool_name'"
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#5227 Add new ML Extension version 2.7.0
  src/index.json
Labels: extension/ml, Machine Learning, Auto-Assign

#5231 {CI} Test auto commit
  text.txt
Labels: CI, Auto-Assign

#5202 [AKS][TA] remove source_resource_id of rolebinding update command
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
Labels: AKS, Auto-Assign

#5233 [k8s-extension] Update extension CLI to v1.3.1
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#5226 VM Repair: Improve vm reset nic command
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/custom.py
  src/vm-repair/setup.py
Labels: Compute, Auto-Assign

#5212 {AKS} Update readme to add dependency description
  src/aks-preview/HISTORY.rst
  src/aks-preview/README.rst
Labels: AKS, Auto-Assign

#5177 Containerapp 0.3.9 Release
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_clients.py
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_params.py
  src/containerapp/azext_containerapp/_utils.py
  src/containerapp/azext_containerapp/_validators.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_container_acr.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_msi.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_commands.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py
  src/containerapp/setup.py
Labels: Auto-Assign, ContainerApp

#5236 [Network] `az network firewall create`: Support Basic SKU creation with management IP configuration
  src/azure-firewall/HISTORY.rst
  src/azure-firewall/azext_firewall/_help.py
  src/azure-firewall/azext_firewall/_params.py
  src/azure-firewall/azext_firewall/custom.py
  src/azure-firewall/azext_firewall/tests/latest/recordings/test_firewall_basic_sku.yaml
  src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
  src/azure-firewall/setup.py
Labels: Network, Auto-Assign

#5240 [ML] Update index for v2.7.1
  src/index.json
Labels: extension/ml, Machine Learning, Auto-Assign

#5245 [k8s-extension] Update extension CLI to v1.3.2
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/custom.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#5249 [IoT] IoT Extension Release v0.17.0
  linter_exclusions.yml
  src/index.json
Labels: IoT/CLI, Auto-Assign

#5248 Update `aks kollect` command to use Periscope version 0.0.10
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/aks_diagnostics.py
Labels: AKS, Auto-Assign

#5256 [k8s-extension] Update extension CLI to v1.3.3
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#5260 [NetworkManager] `az network manager connection management-group`: Reopen the set of commands
  src/network-manager/HISTORY.rst
  src/network-manager/azext_network_manager/_help.py
  src/network-manager/azext_network_manager/_params.py
  src/network-manager/azext_network_manager/azext_metadata.json
  src/network-manager/azext_network_manager/commands.py
  src/network-manager/azext_network_manager/custom.py
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_connection_management.yaml
  src/network-manager/azext_network_manager/tests/latest/test_network_scenario.py
  src/network-manager/setup.py
Labels: Network, Auto-Assign

#5262 Containerapp-compose Release 0.2.1
  scripts/ci/credscan/CredScanSuppressions.json
  src/containerapp-compose/HISTORY.rst
  src/containerapp-compose/azext_containerapp_compose/_monkey_patch.py
  src/containerapp-compose/azext_containerapp_compose/custom.py
  src/containerapp-compose/azext_containerapp_compose/tests/latest/common.py
  src/containerapp-compose/azext_containerapp_compose/tests/latest/recordings/test_containerapp_compose_create_location_differ_from_resource_group.yaml
  src/containerapp-compose/azext_containerapp_compose/tests/latest/recordings/test_containerapp_compose_create_with_resources_from_deploy_with_mismatched_cpu_memory.yaml
  src/containerapp-compose/azext_containerapp_compose/tests/latest/recordings/test_containerapp_compose_create_with_resources_from_service_memory.yaml
  src/containerapp-compose/azext_containerapp_compose/tests/latest/test_containerapp_preview_location.py
  src/containerapp-compose/azext_containerapp_compose/tests/latest/test_containerapp_preview_resources.py
  src/containerapp-compose/setup.py
Labels: Auto-Assign, ContainerApp

#5261 Azure Automation Hybrid Worker resource commands added
  src/automation/HISTORY.rst
  src/automation/README.md
  src/automation/azext_automation/__init__.py
  src/automation/azext_automation/aaz/__init__.py
  src/automation/azext_automation/aaz/latest/__init__.py
  src/automation/azext_automation/aaz/latest/automation/__cmd_group.py
  src/automation/azext_automation/aaz/latest/automation/__init__.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/__cmd_group.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/__init__.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/_create.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/_delete.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/_list.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/_show.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/_update.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/__cmd_group.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/__init__.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_create.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_delete.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_list.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_move.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_show.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_update.py
  src/automation/azext_automation/azext_metadata.json
  src/automation/azext_automation/tests/latest/recordings/test_automation.yaml
  src/automation/azext_automation/tests/latest/test_automation_scenario_manual.py
  src/automation/linter_exclusions.yml
  src/automation/setup.py
Labels: customer-reported

#5266 fixed hybid worker move command
  src/automation/HISTORY.rst
  src/automation/README.md
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_move.py
  src/automation/linter_exclusions.yml
Labels: customer-reported

#5267 updated automation extension version
  src/automation/HISTORY.rst
  src/automation/README.md
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_move.py
  src/automation/setup.py
Labels: customer-reported

#5273 added support for handling success responses on create resources
  src/automation/HISTORY.rst
  src/automation/azext_automation/aaz/latest/automation/hrwg/_create.py
  src/automation/azext_automation/aaz/latest/automation/hrwg/hrw/_create.py
  src/automation/azext_automation/tests/latest/recordings/test_automation.yaml
  src/automation/azext_automation/tests/latest/test_automation_scenario_manual.py
  src/automation/setup.py
Labels: customer-reported

#5276 [AKS]: `az aks update`: Fix: preview naming of mariner v2
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_params.py
Labels: AKS, Auto-Assign

#5283 Updating the fetch_repair_vm to use the small letters in the query in…
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/_validators.py
  src/vm-repair/setup.py
Labels: customer-reported

#5285 [NetworkManager] Fix az network manager resources delete behavior
  src/network-manager/HISTORY.rst
  src/network-manager/azext_network_manager/custom.py
  src/network-manager/setup.py
Labels: Network, Auto-Assign

#5247 Add option for aks node restriction
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_node_restriction.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/linter_exclusions.yml
Labels: AKS, Auto-Assign

#5278 {AKS} Filter out one gpu test case
  src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
  src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
  src/aks-preview/azext_aks_preview/_help.py
Labels: AKS, Auto-Assign

#5281 {AKS} Update min cli core version to 2.38.0
  src/aks-preview/HISTORY.rst
  src/aks-preview/README.rst
  src/aks-preview/azext_aks_preview/azext_metadata.json
Labels: AKS, Auto-Assign

#5291 {CI} Update milestone from Aug 2022 (2022-09-06) to Sep 2022 (2022-10-12) - For Ignite
  .github/fabricbot.json
Labels: CI, Auto-Assign

#5292 {AKS} Release aks-preview
  src/aks-preview/HISTORY.rst
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign
