Repository Azure/azure-cli-extensions, pull requests merged in 2023-12, with the labels that each got.

#7005 [Quota] Add new commands `az quota request list/show` to support managing quota request
  src/quota/HISTORY.rst
  src/quota/azext_quota/__init__.py
  src/quota/azext_quota/aaz/__init__.py
  src/quota/azext_quota/aaz/latest/__init__.py
  src/quota/azext_quota/aaz/latest/quota/__cmd_group.py
  src/quota/azext_quota/aaz/latest/quota/__init__.py
  src/quota/azext_quota/aaz/latest/quota/_create.py
  src/quota/azext_quota/aaz/latest/quota/_list.py
  src/quota/azext_quota/aaz/latest/quota/_show.py
  src/quota/azext_quota/aaz/latest/quota/_update.py
  src/quota/azext_quota/aaz/latest/quota/request/__cmd_group.py
  src/quota/azext_quota/aaz/latest/quota/request/__init__.py
  src/quota/azext_quota/aaz/latest/quota/request/_list.py
  src/quota/azext_quota/aaz/latest/quota/request/_show.py
  src/quota/azext_quota/aaz/latest/quota/usage/__cmd_group.py
  src/quota/azext_quota/aaz/latest/quota/usage/__init__.py
  src/quota/azext_quota/aaz/latest/quota/usage/_list.py
  src/quota/azext_quota/aaz/latest/quota/usage/_show.py
  src/quota/azext_quota/azext_metadata.json
  src/quota/azext_quota/custom.py
  src/quota/azext_quota/generated/_client_factory.py
  src/quota/azext_quota/generated/_help.py
  src/quota/azext_quota/generated/_params.py
  src/quota/azext_quota/generated/action.py
  src/quota/azext_quota/generated/commands.py
  src/quota/azext_quota/generated/custom.py
  src/quota/azext_quota/manual/commands.py
  src/quota/azext_quota/tests/latest/recordings/test_quota_crud.yaml
  src/quota/azext_quota/tests/latest/recordings/test_quota_request.yaml
  src/quota/azext_quota/tests/latest/test_quota_scenario.py
  src/quota/setup.py
Labels: Auto-Assign

#7066 [IoT] Adds IoT Ops extension v0.2.0b1
  src/index.json
Labels: IoT/CLI, Auto-Assign

#7061 [az vm repair] Win-run-driver script fix
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/custom.py
  src/vm-repair/azext_vm_repair/scripts/win-run-driver.ps1
  src/vm-repair/setup.py
Labels: Compute, Auto-Assign

#7072 Arc Appliance CLI 1.0.2 December Release
  src/index.json
Labels: Auto-Assign

#7071 [k8s-extension] Update extension CLI to v1.5.3
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/custom.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/WorkloadIAM.py
  src/k8s-extension/azext_k8s_extension/tests/latest/test_workload_iam.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#7078 [IoT] Add IoT Extension v0.23.1
  src/index.json
Labels: IoT/CLI, Auto-Assign

#6509 {CI} Fix static analysis
  .flake8
  azure-pipelines.yml
  pylintrc
  scripts/ci/azdev_linter_style.py
  scripts/ci/source_code_static_analysis.py
  scripts/ci/test_source.py
Labels: CI, Auto-Assign

#7081 {CI} Regenerating breaking change report with only_break=True to control length within 65535.
  scripts/ci/breaking_change_test.py
Labels: CI, Auto-Assign

#7080 [Quantum] Update version and history info for az quantum extension 0.20.0
  src/quantum/HISTORY.rst
  src/quantum/azext_quantum/__init__.py
  src/quantum/setup.py
Labels: Quantum, Auto-Assign

#6915 Upgrade Helm for connectedk8s
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_constants.py
  src/connectedk8s/azext_connectedk8s/_precheckutils.py
  src/connectedk8s/azext_connectedk8s/_utils.py
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#7092 [az fleet] Minor style & linter updates to fix checks.
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/__init__.py
  src/fleet/azext_fleet/_completers.py
  src/fleet/azext_fleet/_help.py
  src/fleet/azext_fleet/_helpers.py
  src/fleet/azext_fleet/_params.py
  src/fleet/azext_fleet/_validators.py
  src/fleet/azext_fleet/custom.py
  src/fleet/azext_fleet/tests/__init__.py
  src/fleet/azext_fleet/tests/latest/__init__.py
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubful.yaml
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubless.yaml
  src/fleet/azext_fleet/tests/latest/test_fleet_hubful_scenario.py
  src/fleet/azext_fleet/tests/latest/test_fleet_hubless_scenario.py
  src/fleet/azext_fleet/tests/latest/test_validators.py
  src/fleet/setup.py
Labels: Auto-Assign

#7038 [AKS] Fix for `az aks approuting update` command
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_update.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7099 {CI} Add statement for azdev style
  azure-pipelines.yml
Labels: CI, Auto-Assign

#7101 {CI} Add statement for azdev style
  azure-pipelines.yml
  scripts/ci/azdev_linter_style.py
Labels: CI, Auto-Assign

#7103 Properly handle k8s clusters of kind provisioned cluster for connectedk8s
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_client_factory.py
  src/connectedk8s/azext_connectedk8s/_constants.py
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/__init__.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/_configuration.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/_connected_kubernetes_client.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/_patch.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/_serialization.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/_vendor.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/_version.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/models/__init__.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/models/_connected_kubernetes_client_enums.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/models/_models_py3.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/models/_patch.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/operations/__init__.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/operations/_connected_cluster_operations.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/operations/_operations.py
  src/connectedk8s/azext_connectedk8s/vendored_sdks/preview_2023_11_01/operations/_patch.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#7091 {CI} Update bot workflow
  .github/policies/resourceManagement.yml
  .github/workflows/AddIssueComment.yml
  .github/workflows/BlockPRMerge.yml
Labels: CI, Auto-Assign

#7100 [devcenter] Update project environment type parameters to be required
  src/devcenter/HISTORY.rst
  src/devcenter/azext_devcenter/_help.py
  src/devcenter/azext_devcenter/_params.py
  src/devcenter/azext_devcenter/action.py
  src/devcenter/azext_devcenter/custom.py
  src/devcenter/azext_devcenter/tests/latest/test_devcenter_scenario.py
  src/devcenter/setup.py
Labels: Auto-Assign

#7098 [Spring] Add new params to support auto binding
  src/spring/HISTORY.md
  src/spring/azext_spring/_app_factory.py
  src/spring/azext_spring/_help.py
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/_validators_enterprise.py
  src/spring/azext_spring/app.py
  src/spring/azext_spring/tests/latest/recordings/test_app_create_binding_tanzu_components.yaml
  src/spring/azext_spring/tests/latest/test_asa_app.py
  src/spring/azext_spring/tests/latest/test_asa_app_scenario.py
  src/spring/setup.py
Labels: Auto-Assign

#7021 [Spring] Support managed component log stream
  src/spring/HISTORY.md
  src/spring/azext_spring/_help.py
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/app.py
  src/spring/azext_spring/commands.py
  src/spring/azext_spring/custom.py
  src/spring/azext_spring/log_stream/__init__.py
  src/spring/azext_spring/log_stream/log_stream_operations.py
  src/spring/azext_spring/log_stream/writer.py
  src/spring/azext_spring/managed_components/__init__.py
  src/spring/azext_spring/managed_components/managed_component.py
  src/spring/azext_spring/managed_components/managed_component_operations.py
  src/spring/azext_spring/managed_components/validators_managed_component.py
  src/spring/azext_spring/tests/latest/managed_component/__init__.py
  src/spring/azext_spring/tests/latest/managed_component/test_managed_component_scenarios.py
  src/spring/azext_spring/tests/latest/managed_component/test_managed_component_validators.py
  src/spring/azext_spring/tests/latest/managed_component/test_writer.py
  src/spring/setup.py
Labels: Auto-Assign

#7115 {AKS} Fix azdev style issues for tests
  src/aks-preview/azext_aks_preview/tests/latest/recording_processors.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py
  src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py
  src/aks-preview/azext_aks_preview/tests/latest/test_maintenanceconfiguration.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
Labels: AKS, Auto-Assign

#6987 {AKS} Replace Workload Identity related functions in aks-preview with azure-cli
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7131 {CI} Add build wheel check and extension name check
  scripts/ci/azdev_linter_style.py
Labels: CI, Auto-Assign

#7117 {AKS} Fix azdev style issues for azuremonitormetrics
  src/aks-preview/azext_aks_preview/azuremonitormetrics/addonput.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/amg/link.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/amw/create.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/amw/defaults.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/amw/helper.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/constants.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/dce_api.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/dcr_api.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/dcra_api.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/defaults.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/dc/delete.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/helper.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/recordingrules/create.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/recordingrules/delete.py
  src/aks-preview/azext_aks_preview/azuremonitormetrics/responseparsers/amwlocationresponseparser.py
Labels: AKS, Auto-Assign

#7118 {AKS} Fix azdev style issues for azurecontainerstorage
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
Labels: AKS, Auto-Assign

#7121 {AKS} Fix azdev style issues for diagnostics & draft
  src/aks-preview/azext_aks_preview/aks_diagnostics.py
  src/aks-preview/azext_aks_preview/aks_draft/commands.py
Labels: AKS, Auto-Assign

#7124 {AKS} Fix azdev style issues for internal files
  src/aks-preview/azext_aks_preview/__init__.py
  src/aks-preview/azext_aks_preview/_client_factory.py
  src/aks-preview/azext_aks_preview/_completers.py
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_format.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_helpers.py
  src/aks-preview/azext_aks_preview/_loadbalancer.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_podidentity.py
  src/aks-preview/azext_aks_preview/_roleassignments.py
  src/aks-preview/azext_aks_preview/_validators.py
Labels: AKS, Auto-Assign
