Repository Azure/azure-cli-extensions, pull requests merged in 2023-09, with the labels that each got.

#6649 [vm-repair] arm64 support And Bug Fix for telemetry
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/command_helper_class.py
  src/vm-repair/azext_vm_repair/custom.py
  src/vm-repair/azext_vm_repair/repair_utils.py
  src/vm-repair/azext_vm_repair/scripts/win-enable-nested-hyperv.ps1
  src/vm-repair/azext_vm_repair/telemetry.py
  src/vm-repair/azext_vm_repair/tests/latest/test_repair_commands.py
  src/vm-repair/setup.py
Labels: Auto-Assign

#6716 [k8s-extension] Update extension CLI to v1.4.4
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/azext_metadata.json
  src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
Labels: Auto-Assign

#6717 Make error message for `az spring app logs` more readable.
  src/spring/HISTORY.md
  src/spring/azext_spring/custom.py
  src/spring/setup.py
Labels: Auto-Assign

#6718 [k8s-extension] Fix bugs while dropping 'azure-mgmt-relay'
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/setup.py
Labels: Auto-Assign

#6720 {containerapp} az containerapp update fix list secret value for populate
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/containerapp_decorator.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_container_app_mount_azurefile_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_with_workloadprofile_yaml.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_with_yaml.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_preview_create_with_yaml.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
  src/containerapp/setup.py
Labels: Auto-Assign, ContainerApp

#6719 {AKS} Update AKS tests to allow enable AAD legacy when creating cluster
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#6725 {AKS} Update history to add a table of releases and adopted API versions
  src/aks-preview/HISTORY.rst
  src/aks-preview/README.rst
Labels: AKS, Auto-Assign

#6696 {containerapp} support connected env command group
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_client_factory.py
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/_models.py
  src/containerapp/azext_containerapp/_params.py
  src/containerapp/azext_containerapp/_utils.py
  src/containerapp/azext_containerapp/_validators.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/connected_env_decorator.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_preview_environment_type.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_preview_scenario.py
  src/containerapp/azext_containerapp/vendored_sdks/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/_configuration.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/_source_control_configuration_client.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/_version.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/aio/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/aio/_configuration.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/aio/_source_control_configuration_client.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/models.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/_configuration.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/_patch.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/_source_control_configuration_client.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/_vendor.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/_version.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/_configuration.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/_patch.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/_source_control_configuration_client.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/operations/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/operations/_extensions_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/operations/_flux_config_operation_status_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/operations/_flux_configurations_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/operations/_operation_status_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/operations/_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/aio/operations/_source_control_configurations_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/models/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/models/_models_py3.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/models/_source_control_configuration_client_enums.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/operations/__init__.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/operations/_extensions_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/operations/_flux_config_operation_status_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/operations/_flux_configurations_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/operations/_operation_status_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/operations/_operations.py
  src/containerapp/azext_containerapp/vendored_sdks/kubernetesconfiguration/v2022_03_01/operations/_source_control_configurations_operations.py
  src/containerapp/test_container_app_mount_azurefile_e2e_containerapp.yml
  src/containerapp/test_containerapp_create_with_yaml_containerapp.yml
Labels: Auto-Assign, ContainerApp

#6629 Add az aks ai command
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_openai_wrapper.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6729 Update _params.py
  src/communication/azext_communication/manual/_params.py
Labels: customer-reported

#6734 {CI} Update bot policy
  .github/policies/resourceManagement.yml
Labels: CI, Auto-Assign

#6744 Update validation for ASM Pluginca feature
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_pluginca.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#6745 [Spring] help customers register AKS RP when creating VNET instance
  src/spring/azext_spring/_constant.py
  src/spring/azext_spring/_utils.py
  src/spring/azext_spring/spring_instance.py
Labels: AKS, Auto-Assign

#6679 {Application-insights} Migrate application-insights to AAZ
  src/application-insights/HISTORY.rst
  src/application-insights/azext_applicationinsights/__init__.py
  src/application-insights/azext_applicationinsights/_client_factory.py
  src/application-insights/azext_applicationinsights/_help.py
  src/application-insights/azext_applicationinsights/aaz/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/__cmd_group.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/__cmd_group.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/api_key/__cmd_group.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/api_key/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/api_key/_create.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/api_key/_delete.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/api_key/_list.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/__cmd_group.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/billing/__cmd_group.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/billing/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/billing/_show.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/billing/_update.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/continues_export/__cmd_group.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/continues_export/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/continues_export/_delete.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/continues_export/_list.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/continues_export/_show.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/linked_storage/__cmd_group.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/linked_storage/__init__.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/linked_storage/_link.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/linked_storage/_show.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/linked_storage/_unlink.py
  src/application-insights/azext_applicationinsights/aaz/latest/monitor/app_insights/component/linked_storage/_update.py
  src/application-insights/azext_applicationinsights/azext_metadata.json
  src/application-insights/azext_applicationinsights/commands.py
  src/application-insights/azext_applicationinsights/custom.py
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_api_key.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_appinsights_webtest_crud.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_continues_export.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_storage.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_workspace.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_public_network_access.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_function.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_function_cross_resource_groups.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_webapp.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_webapp_cross_resource_group.yaml
  src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py
  src/application-insights/azext_applicationinsights/util.py
  src/application-insights/setup.py
Labels: Monitor, Auto-Assign

#6728 [Spring] certificate - Add argument `--auto-sync` and new command `update`
  src/spring/HISTORY.md
  src/spring/azext_spring/_help.py
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/commands.py
  src/spring/azext_spring/custom.py
  src/spring/azext_spring/tests/latest/test_asa_certificate.py
  src/spring/azext_spring/vendored_sdks/appplatform/v2023_09_01_preview/aio/operations/_services_operations.py
  src/spring/azext_spring/vendored_sdks/appplatform/v2023_09_01_preview/models/__init__.py
  src/spring/azext_spring/vendored_sdks/appplatform/v2023_09_01_preview/models/_app_platform_management_client_enums.py
  src/spring/azext_spring/vendored_sdks/appplatform/v2023_09_01_preview/models/_models_py3.py
  src/spring/azext_spring/vendored_sdks/appplatform/v2023_09_01_preview/operations/_services_operations.py
Labels: Auto-Assign

#6737 Make sure the resource created for the Public IP match the name repai…
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/_validators.py
  src/vm-repair/setup.py
Labels: Compute, Auto-Assign

#6748 {Service Connector}: fix passwordless postgres cmd
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/custom.py
Labels: Auto-Assign

#6754 {CI} Update index.json
  src/index.json
Labels: CI, Auto-Assign

#6574 containerapp - Add --source and --repo to containerapp create/update
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/_params.py
  src/containerapp/azext_containerapp/_up_utils.py
  src/containerapp/azext_containerapp/_validators.py
  src/containerapp/azext_containerapp/containerapp_decorator.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_repo_and_connected_environment_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_repo_and_yaml_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_repo_with_non_ACR_registry_server_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_and_connected_environment_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_and_image_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_and_repo_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_and_yaml_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_with_Dockerfile_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_with_acr_task_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_with_buildpack_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_with_non_ACR_registry_server_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_create_source_without_ACR_registry_server_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_create_update_with_source.py
  src/containerapp/azext_containerapp/tests/latest/utils.py
Labels: Auto-Assign, ContainerApp

#6713 [Network-Manager] Fix #27299: `az network manager group static-member create` and `az network manager post-commit`
  src/network-manager/HISTORY.rst
  src/network-manager/azext_network_manager/aaz/latest/network/manager/_post_commit.py
  src/network-manager/azext_network_manager/commands.py
  src/network-manager/azext_network_manager/custom.py
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_connect_config_crud.yaml
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_static_member_crud.yaml
  src/network-manager/azext_network_manager/tests/latest/test_network_scenario.py
  src/network-manager/setup.py
Labels: Network, Auto-Assign

#6726 [containerapp] Add Support for Qdrant dev service
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_service_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Labels: customer-reported, Auto-Assign, ContainerApp

#6706 [AKS] az aks update: add new parameter `--disable-workload-identity` to disable Workload Identity
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6756 Add validation for `az webapp scale`
  .github/CODEOWNERS
  src/appservice-kube/HISTORY.rst
  src/appservice-kube/azext_appservice_kube/_help.py
  src/appservice-kube/azext_appservice_kube/custom.py
  src/appservice-kube/setup.py
Labels: extension/webapp, App Services, Web Apps, Auto-Assign

#6767 {AKS} Refresh vendored SDK
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2023_07_02_preview/models/_models_py3.py
Labels: AKS, Auto-Assign

#6755 [Spring] Use service fqdn to call logstream
  src/spring/azext_spring/_log_stream.py
Labels: Auto-Assign

#6750 capture az error output and auto-fix the script
  src/aks-preview/azext_aks_preview/_openai_wrapper.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#6757 Add new command `az spring list-support-server-versions`
  src/spring/HISTORY.md
  src/spring/azext_spring/_help.py
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/_transformers.py
  src/spring/azext_spring/commands.py
  src/spring/azext_spring/spring_instance.py
  src/spring/azext_spring/tests/latest/recordings/test_list_support_server_versions.yaml
  src/spring/azext_spring/tests/latest/test_asa_server_version.py
Labels: Auto-Assign

#6768 Add enable ASM egress gateway commands for az aks mesh
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_egress_gateway.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6773 revert az aks copilot
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_openai_wrapper.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6778 Skip onboarding prechecks for AKS-HCI
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/setup.py
Labels: AKS, Auto-Assign

#6784 [AKS] Custom ips and managed ips can be assigned to aks cluster outbound resources
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_loadbalancer.py
  src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6769 Fleet CLI update
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/_params.py
  src/fleet/azext_fleet/_validators.py
  src/fleet/azext_fleet/custom.py
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet.yaml
  src/fleet/azext_fleet/tests/latest/test_fleet_scenario.py
  src/fleet/azext_fleet/tests/latest/test_validators.py
  src/fleet/linter_exclusions.yml
  src/fleet/setup.py
Labels: Auto-Assign

#6797 Abiyer/skip precheck for akshci
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#6799 Fix `az spring list-marketplace-plan` command unexpected error
  src/spring/HISTORY.md
  src/spring/azext_spring/_marketplace.py
  src/spring/setup.py
Labels: Auto-Assign

#6795 fleet argument documentation update
  src/fleet/azext_fleet/_params.py
Labels: Auto-Assign

#6777 machine api cli: code changes
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_client_factory.py
  src/aks-preview/azext_aks_preview/_format.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_machine_cmds.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: customer-reported

#6805 [AKS] support premium tier and add supportPlan
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_premium_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_premium_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6800 {Service Connector} fix postgres command error
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign, Service Connector

#6811 [IoT] IoT Extension Release v0.22.0
  src/index.json
Labels: IoT/CLI, Auto-Assign

#6812 {CI} Take over all CXP Attention issues
  .github/policies/resourceManagement.yml
Labels: CI, Auto-Assign

#6677 enforce valid custom locations SP app object id
  src/connectedk8s/.gitignore
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_utils.py
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/azext_connectedk8s/tests/latest/README.md
  src/connectedk8s/azext_connectedk8s/tests/latest/config.json.dist
  src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#6813 {CI} Update policy configuration according to Service-Contact-List wiki
  .github/policies/resourceManagement.yml
Labels: CI, Auto-Assign

#6817 revert connectedk8s cli version from 1.5.0 to 1.4.2
  src/index.json
Labels: Connected Kubernetes, Auto-Assign
