Repository Azure/azure-cli-extensions, pull requests merged in 2023-10, with the labels that each got.

#6822 [AKS Fleet] Fix broken --node-image-selection
  src/fleet/azext_fleet/custom.py
Labels: AKS, Auto-Assign

#6823 [AKS Fleet] Version bump
  src/fleet/HISTORY.rst
  src/fleet/setup.py
Labels: AKS, Auto-Assign

#6827 chore: `ml` extension 2.21.0 release
  src/index.json
Labels: extension/ml, Machine Learning, Auto-Assign

#6834 revert connectedk8s 1.5.1
  src/index.json
Labels: Connected Kubernetes, Auto-Assign

#6833 revert 8ace62a472ee763e319f3e09964472f9427be0f2, except test changes
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_utils.py
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/azext_connectedk8s/tests/latest/README.md
  src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#6840 [containerapp] `az containerapp job create`: Fix AttributeError when `--trigger-type` is None
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/containerapp_env_decorator.py
  src/containerapp/azext_containerapp/containerapp_job_decorator.py
Labels: Auto-Assign, ContainerApp

#6842 {CI} Add new comment to explain the reason that pin the wheel to 0.30.0
  .github/pull_request_template.md
  scripts/ci/test_index.py
Labels: CI, Auto-Assign

#6841 {Service Connector} support webapp slot and rollback get identity operation
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/azext_metadata.json
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/custom.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#6844 {AKS} Replace Image Cleaner related functions in aks-preview with azure-cli ones
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6344 remove preview tag
  src/traffic-collector/HISTORY.rst
  src/traffic-collector/azext_traffic_collector/azext_metadata.json
  src/traffic-collector/setup.py
Labels: customer-reported

#6849 [Arc Appliance] Releasing ArcAppliance 1.0.0 October GA Release
  src/index.json
Labels: Auto-Assign

#6853 {containerapp} Improve tests: Use same name foo for compose tests
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_basic_no_existing_resources.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_environment.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_environment_prompt.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_ingress_both.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_ingress_external.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_ingress_internal.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_ingress_prompt.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_registry_all_args.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_registry_server_arg_only.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_replicas_global_scale.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_replicas_replicated_mode.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_resources_from_both_cpus_and_deploy_cpu.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_resources_from_deploy_cpu.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_resources_from_service_cpus.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_secrets.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_secrets_and_existing_environment.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_secrets_and_existing_environment_conflict.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_transport_arg.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_create_with_transport_mapping_arg.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_with_command_list.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_with_command_list_and_entrypoint.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_compose_with_command_string.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_basic.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_command.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_environment.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_ingress.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_registries.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_resources.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_scale.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_secrets.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_compose_transport_overrides.py
Labels: Auto-Assign, ContainerApp

#6854 [connectedvmware] Using stable swagger in vendored_sdks
  src/connectedvmware/azext_connectedvmware/tests/latest/recordings/test_connectedvmware.yaml
  src/connectedvmware/azext_connectedvmware/tests/latest/test_connectedvmware_scenario.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/_azure_arc_vmware_management_service_api.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/_configuration.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/_patch.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/_azure_arc_vmware_management_service_api.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/_configuration.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/_patch.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/__init__.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_azure_arc_vmware_management_service_api_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_clusters_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_datastores_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_guest_agents_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_hosts_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_hybrid_identity_metadata_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_inventory_items_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_machine_extensions_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_resource_pools_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_vcenters_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_virtual_machine_instances_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_virtual_machine_templates_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_virtual_machines_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_virtual_networks_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_vm_instance_guest_agents_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/aio/operations/_vm_instance_hybrid_identity_metadata_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/models/__init__.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/models/_azure_arc_vmware_management_service_api_enums.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/models/_models.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/models/_models_py3.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/__init__.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_azure_arc_vmware_management_service_api_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_clusters_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_datastores_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_guest_agents_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_hosts_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_hybrid_identity_metadata_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_inventory_items_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_machine_extensions_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_resource_pools_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_vcenters_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_virtual_machine_instances_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_virtual_machine_templates_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_virtual_machines_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_virtual_networks_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_vm_instance_guest_agents_operations.py
  src/connectedvmware/azext_connectedvmware/vendored_sdks/connectedvmware/operations/_vm_instance_hybrid_identity_metadata_operations.py
Labels: Auto-Assign

#6775 Add mesh upgrade commands for az aks mesh
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_format.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_get_revisions.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_get_upgrades.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6816 Display error messages from tenant for "/api/rdpfile"
  src/bastion/azext_bastion/custom.py
  src/bastion/azext_bastion/tests/latest/recordings/test_bastion_host_crud.yaml
Labels: customer-reported

#6861 {containerapp} Fix history
  src/containerapp/HISTORY.rst
Labels: Auto-Assign, ContainerApp

#6859 {AKS} Fix #27461 `az aks create`: Update help information for option `--node-osdisk-size`
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
Labels: AKS, Auto-Assign

#6830 [AKS Fleet] Update for Fleet identity options.
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/_help.py
  src/fleet/azext_fleet/_params.py
  src/fleet/azext_fleet/_validators.py
  src/fleet/azext_fleet/commands.py
  src/fleet/azext_fleet/custom.py
  src/fleet/azext_fleet/tests/latest/test_fleet_hubful_scenario.py
  src/fleet/azext_fleet/tests/latest/test_fleet_hubless_scenario.py
  src/fleet/azext_fleet/tests/latest/test_validators.py
  src/fleet/setup.py
Labels: AKS, Auto-Assign

#6866 Add 2.21.1 ml extension release
  src/index.json
Labels: extension/ml, Machine Learning, Auto-Assign

#6837 AKS: Implement support to perform Azure container storage operations
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_client_factory.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/__init__.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_consts.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6883 AKS: Rearrange a few helm values for Azure container storage
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#6886 [az fleet] GA Update & --vm-size
  .github/CODEOWNERS
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/_params.py
  src/fleet/azext_fleet/_validators.py
  src/fleet/azext_fleet/azext_metadata.json
  src/fleet/azext_fleet/commands.py
  src/fleet/azext_fleet/custom.py
  src/fleet/azext_fleet/tests/latest/test_fleet_hubful_scenario.py
  src/fleet/azext_fleet/tests/latest/test_fleet_hubless_scenario.py
  src/fleet/azext_fleet/tests/latest/test_validators.py
  src/fleet/setup.py
Labels: Auto-Assign

#6863 [containerapp] az containerapp service milvus: Add support for milvus dev service
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_service_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Labels: customer-reported

#6887 Network Fabric Extension: Reverting attribute name change back as we need to keep the swagger naming in managed network fabric extension.
  linter_exclusions.yml
  src/managednetworkfabric/HISTORY.rst
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/acl/_create.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/acl/_update.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/ipcommunity/_create.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/ipcommunity/_update.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/ipextendedcommunity/_create.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/ipextendedcommunity/_update.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/taprule/_create.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/taprule/_update.py
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/recordings/test_GA_accesscontrollists_scenario1.yaml
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/recordings/test_GA_ipcommunity_scenario1.yaml
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/recordings/test_GA_ipextendedcommunity_scenario1.yaml
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/recordings/test_GA_taprule_scenario1.yaml
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/test_acl.py
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/test_ipcommunity.py
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/test_ipextendedcommunity.py
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/test_taprule.py
  src/managednetworkfabric/setup.py
Labels: Network, Auto-Assign

#6893 Revert "[containerapp] az containerapp service milvus: Add support for milvus dev service (#6863)
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_service_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Labels: Auto-Assign, ContainerApp

#6873 Update API for Aks Edge Essentials
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/setup.py
Labels: AKS, Auto-Assign

#6867 [containerapp] Hide containerapps and jobs env vars on create and update
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_transformers.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_container_acr.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_eventjob_crudoperations_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_scale_create.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_scenario.py
  src/containerapp/azext_containerapp/tests/latest/test_containerappjob_event_triggered_crud.py
Labels: Auto-Assign, ContainerApp

#6897 [dataprotection] Added '-v' option for all --vault-name parameters
  src/dataprotection/HISTORY.rst
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_adhoc_backup.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_create.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_delete.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_list.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_resume_protection.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_show.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_stop_protection.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_suspend_backup.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_update.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_validate_for_backup.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_validate_for_restore.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/_wait.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/deleted_backup_instance/_list.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/deleted_backup_instance/_show.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/deleted_backup_instance/_undelete.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_instance/restore/_trigger.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_policy/_create.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_policy/_delete.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_policy/_list.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_policy/_show.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/backup_policy/_update.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/job/_list.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/job/_show.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/recovery_point/_list.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/recovery_point/_show.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/resource_guard/_list.py
  src/dataprotection/azext_dataprotection/aaz/latest/dataprotection/restorable_time_range/_find.py
  src/dataprotection/setup.py
Labels: Data Protection, Auto-Assign

#6913 [IoT] IoT Extension Release v0.23.0
  src/index.json
Labels: IoT/CLI, Auto-Assign

#6896 Add deterministic outbound IP optional arg to 'grafana create' command
  src/amg/HISTORY.rst
  src/amg/README.md
  src/amg/azext_amg/_params.py
  src/amg/azext_amg/custom.py
  src/amg/azext_amg/tests/latest/recordings/test_amg_backup_restore.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_crud.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_api_key_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_service_account_e2e.yaml
  src/amg/setup.py
Labels: extension/grafana, Auto-Assign

#6911 AKS: Fix scenarios around nodepool and storagepool name for Azure Container Storage
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_consts.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign
