Repository Azure/azure-cli-extensions, pull requests merged in 2024-10, with the labels that each got.

#8001 {log-analytics} Migrate to AAZ CodeGen
  src/log-analytics/HISTORY.rst
  src/log-analytics/azext_loganalytics/__init__.py
  src/log-analytics/azext_loganalytics/_client_factory.py
  src/log-analytics/azext_loganalytics/_format.py
  src/log-analytics/azext_loganalytics/_help.py
  src/log-analytics/azext_loganalytics/aaz/__init__.py
  src/log-analytics/azext_loganalytics/aaz/latest/__init__.py
  src/log-analytics/azext_loganalytics/aaz/latest/_clients.py
  src/log-analytics/azext_loganalytics/aaz/latest/monitor/__cmd_group.py
  src/log-analytics/azext_loganalytics/aaz/latest/monitor/__init__.py
  src/log-analytics/azext_loganalytics/aaz/latest/monitor/log_analytics/__cmd_group.py
  src/log-analytics/azext_loganalytics/aaz/latest/monitor/log_analytics/__init__.py
  src/log-analytics/azext_loganalytics/aaz/latest/monitor/log_analytics/_query.py
  src/log-analytics/azext_loganalytics/azext_metadata.json
  src/log-analytics/azext_loganalytics/commands.py
  src/log-analytics/azext_loganalytics/custom.py
  src/log-analytics/azext_loganalytics/tests/latest/recordings/test_query.yaml
  src/log-analytics/azext_loganalytics/tests/latest/test_loganalytics_commands.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/__init__.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/log_analytics_data_client.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/__init__.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/column.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/column_py3.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/error_detail.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/error_detail_py3.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/error_info.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/error_info_py3.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/error_response.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/error_response_py3.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/query_body.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/query_body_py3.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/query_results.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/query_results_py3.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/table.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/models/table_py3.py
  src/log-analytics/azext_loganalytics/vendored_sdks/loganalytics/version.py
  src/log-analytics/setup.py
Labels: Code Gen, Auto-Assign

#8022 [NetAppFiles] Add splitclonefromparent and list-quota-report commands to volume
  src/netappfiles-preview/HISTORY.rst
  src/netappfiles-preview/azext_netappfiles_preview/aaz/latest/netappfiles/account/_list.py
  src/netappfiles-preview/azext_netappfiles_preview/aaz/latest/netappfiles/volume/__init__.py
  src/netappfiles-preview/azext_netappfiles_preview/aaz/latest/netappfiles/volume/_create.py
  src/netappfiles-preview/azext_netappfiles_preview/aaz/latest/netappfiles/volume/_list_quota_report.py
  src/netappfiles-preview/azext_netappfiles_preview/aaz/latest/netappfiles/volume/_splitclonefromparent.py
  src/netappfiles-preview/azext_netappfiles_preview/tests/latest/test_volume_commands_ext.py
  src/netappfiles-preview/setup.py
Labels: Auto-Assign

#8039 Email Service - Update to email SDK version to 1.0.1b1 and inline att
  src/communication/HISTORY.rst
  src/communication/azext_communication/manual/_params.py
  src/communication/azext_communication/manual/custom.py
  src/communication/azext_communication/version.py
Labels: customer-reported

#7662 [Elastic-SAN] `az elastic-san volume-group create/update`: Add `--enforce-data-integrity-check-for-iscsi`
  src/elastic-san/HISTORY.rst
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_list_sku.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_update.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_wait.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_update.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_wait.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_wait.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_update.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_wait.py
  src/elastic-san/azext_elastic_san/azext_metadata.json
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_customer_managed_key_system_assigned_identity_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_customer_managed_key_user_assigned_identity_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_snapshot_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_volume_group_and_volume_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/test_elastic_san.py
  src/elastic-san/setup.py
Labels: skip-cal-version, stable

#8056 {AKS} Add live test scenario for Windows GPU driver selection feature
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_gpu_driver_type.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#8031 {managementpartner} Migrate to AAZ Codegen
  src/managementpartner/HISTORY.rst
  src/managementpartner/azext_managementpartner/__init__.py
  src/managementpartner/azext_managementpartner/_client_factory.py
  src/managementpartner/azext_managementpartner/_exception_handler.py
  src/managementpartner/azext_managementpartner/_help.py
  src/managementpartner/azext_managementpartner/aaz/__init__.py
  src/managementpartner/azext_managementpartner/aaz/latest/__init__.py
  src/managementpartner/azext_managementpartner/aaz/latest/managementpartner/__cmd_group.py
  src/managementpartner/azext_managementpartner/aaz/latest/managementpartner/__init__.py
  src/managementpartner/azext_managementpartner/aaz/latest/managementpartner/_create.py
  src/managementpartner/azext_managementpartner/aaz/latest/managementpartner/_delete.py
  src/managementpartner/azext_managementpartner/aaz/latest/managementpartner/_list.py
  src/managementpartner/azext_managementpartner/aaz/latest/managementpartner/_show.py
  src/managementpartner/azext_managementpartner/aaz/latest/managementpartner/_update.py
  src/managementpartner/azext_managementpartner/azext_metadata.json
  src/managementpartner/azext_managementpartner/commands.py
  src/managementpartner/azext_managementpartner/custom.py
  src/managementpartner/azext_managementpartner/managementpartner/__init__.py
  src/managementpartner/azext_managementpartner/managementpartner/ace_provisioning_management_partner_api.py
  src/managementpartner/azext_managementpartner/managementpartner/models/__init__.py
  src/managementpartner/azext_managementpartner/managementpartner/models/error.py
  src/managementpartner/azext_managementpartner/managementpartner/models/extended_error_info.py
  src/managementpartner/azext_managementpartner/managementpartner/models/operation_display.py
  src/managementpartner/azext_managementpartner/managementpartner/models/operation_response.py
  src/managementpartner/azext_managementpartner/managementpartner/models/operation_response_paged.py
  src/managementpartner/azext_managementpartner/managementpartner/models/partner_response.py
  src/managementpartner/azext_managementpartner/managementpartner/operations/__init__.py
  src/managementpartner/azext_managementpartner/managementpartner/operations/operation_operations.py
  src/managementpartner/azext_managementpartner/managementpartner/operations/partner_operations.py
  src/managementpartner/azext_managementpartner/managementpartner/version.py
  src/managementpartner/setup.py
Labels: Code Gen, Auto-Assign

#8021 {AKS} Update tests to use vnet integration
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7967 Remove MSAL token Workaround
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_clientproxyutils.py
  src/connectedk8s/azext_connectedk8s/azext_metadata.json
  src/connectedk8s/setup.py
Labels: skip-cal-version

#8043 changed param description for kb-numbers-to-include
  src/maintenance/HISTORY.rst
  src/maintenance/azext_maintenance/aaz/latest/maintenance/applyupdate/_create_or_update.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/applyupdate/_update.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/assignment/_create_or_update_resource_group.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/assignment/_create_or_update_subscription.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/assignment/_update_resource_group.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/assignment/_update_subscription.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/configuration/_create.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/scheduledevent/__cmd_group.py
  src/maintenance/azext_maintenance/aaz/latest/maintenance/scheduledevent/_acknowledge.py
  src/maintenance/azext_maintenance/azext_metadata.json
  src/maintenance/azext_maintenance/tests/latest/recordings/test_maintenance_Scenario.yaml
  src/maintenance/azext_maintenance/tests/latest/test_maintenance_scenario.py
  src/maintenance/setup.py
Labels: minor

#8108 [arc-multicloud] Improvement, Bugfix and Add Customization
  src/multicloud-connector/HISTORY.rst
  src/multicloud-connector/azext_multicloud_connector/_help.py
  src/multicloud-connector/azext_multicloud_connector/_params.py
  src/multicloud-connector/azext_multicloud_connector/_utils.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/_generate_aws_template.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_create.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_delete.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_list.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_show.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_test_permission.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_update.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/public_cloud_connector/_wait.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_create.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_delete.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_list.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_show.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_sync_now.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_configuration/_update.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_type/_list.py
  src/multicloud-connector/azext_multicloud_connector/aaz/latest/arc_multicloud/solution_type/_show.py
  src/multicloud-connector/azext_multicloud_connector/azext_metadata.json
  src/multicloud-connector/azext_multicloud_connector/commands.py
  src/multicloud-connector/azext_multicloud_connector/custom.py
  src/multicloud-connector/azext_multicloud_connector/tests/latest/recordings/test_public_cloud_connector.yaml
  src/multicloud-connector/azext_multicloud_connector/tests/latest/recordings/test_solution_configuration.yaml
  src/multicloud-connector/azext_multicloud_connector/tests/latest/recordings/test_solution_types.yaml
  src/multicloud-connector/azext_multicloud_connector/tests/latest/test_multicloud_connector.py
  src/multicloud-connector/setup.py
Labels: stable

#8125 {CI} Update AddPRComment.yml
  .github/workflows/AddPRComment.yml
Labels: CI, Auto-Assign

#8026 [connectedmachine] release stable version 2024-07-10
  src/connectedmachine/HISTORY.rst
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_assess_patches.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_delete.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_install_patches.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_update.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_upgrade_extension.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/_create.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/_delete.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/_update.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/_wait.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/image/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/extension/image/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/license/_create.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/license/_delete.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/license/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/license/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/license/_update.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/license/_wait.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_endpoint_connection/_delete.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_endpoint_connection/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_endpoint_connection/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_endpoint_connection/_update.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_endpoint_connection/_wait.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_resource/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_resource/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/_create.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/_delete.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/_update.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/_wait.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/network_security_perimeter_configuration/__init__.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/network_security_perimeter_configuration/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/network_security_perimeter_configuration/_reconcile.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/private_link_scope/network_security_perimeter_configuration/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/run_command/__cmd_group.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/run_command/__init__.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/run_command/_create.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/run_command/_list.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/run_command/_show.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/run_command/_update.py
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/run_command/_wait.py
  src/connectedmachine/azext_connectedmachine/azext_metadata.json
  src/connectedmachine/azext_connectedmachine/tests/latest/recordings/test_esu_license.yaml
  src/connectedmachine/azext_connectedmachine/tests/latest/recordings/test_machine_and_extension.yaml
  src/connectedmachine/azext_connectedmachine/tests/latest/recordings/test_netowrk_configuration.yaml
  src/connectedmachine/azext_connectedmachine/tests/latest/recordings/test_private_link.yaml
  src/connectedmachine/azext_connectedmachine/tests/latest/recordings/test_run_command.yaml
  src/connectedmachine/azext_connectedmachine/tests/latest/test_ConnectedMachineAndExtension_scenario.py
  src/connectedmachine/azext_connectedmachine/tests/latest/test_ESULicense_scenario.py
  src/connectedmachine/azext_connectedmachine/tests/latest/test_NetworkConfigurationPerimeter_scenario.py
  src/connectedmachine/azext_connectedmachine/tests/latest/test_PrivateLinkAndPrivateEndpointConnection_scenario.py
  src/connectedmachine/setup.py
Labels: Auto-Assign, stable

#8129 {CI} Update CredScanSuppressions.json
  scripts/ci/credscan/CredScanSuppressions.json
Labels: CI, Auto-Assign

#8130 {ServiceConnector-passwordless}: update dependencies
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#8142 [k8s-extension] Update extension CLI to v1.6.2
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/EntraWorkloadIAM.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/azuremonitormetrics/azuremonitorprofile.py
  src/k8s-extension/azext_k8s_extension/tests/latest/test_entra_workload_iam.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#8145 [Quantum] Remove msrestazure dependency
  src/quantum/azext_quantum/operations/workspace.py
Labels: Quantum, Auto-Assign

#8113 [Quantum] Quantum CLI Extension Release, Version 1.0.0b4
  src/quantum/HISTORY.rst
  src/quantum/azext_quantum/__init__.py
  src/quantum/setup.py
Labels: Quantum, Auto-Assign

#8147 {dataprotection} Remove dependency on `msrestazure.tools`
  src/dataprotection/HISTORY.rst
  src/dataprotection/azext_dataprotection/manual/custom.py
  src/dataprotection/azext_dataprotection/manual/helpers.py
  src/dataprotection/setup.py
Labels: Data Protection, Auto-Assign

#8152 {Containerapp} Remove secrets
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_private_registry_port.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_registry_acr_look_up_credentical.yaml
Labels: Auto-Assign, ContainerApp

#8140 Email service - send email with attachments bug fix
  src/communication/HISTORY.rst
  src/communication/azext_communication/manual/_params.py
  src/communication/azext_communication/manual/custom.py
  src/communication/azext_communication/version.py
Labels: customer-reported

#8159 {Containerapp} Remove secrets
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_gateway_for_spring_component.yaml
Labels: Auto-Assign, ContainerApp

#8143 {azure bastion} Remove dependency on msazurerest
  src/bastion/HISTORY.rst
  src/bastion/azext_bastion/custom.py
  src/bastion/azext_bastion/tests/latest/recordings/test_bastion_host_crud.yaml
  src/bastion/azext_bastion/tunnel.py
  src/bastion/setup.py
Labels: Network, Auto-Assign

#8157 [Elastic-SAN] `az elastic-san create/update`: Support AutoScale features
  src/elastic-san/HISTORY.rst
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_list_sku.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_update.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/_wait.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_update.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/_wait.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume/snapshot/_wait.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_create.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_delete.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_list.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_show.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_update.py
  src/elastic-san/azext_elastic_san/aaz/latest/elastic_san/volume_group/_wait.py
  src/elastic-san/azext_elastic_san/azext_metadata.json
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_customer_managed_key_system_assigned_identity_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_customer_managed_key_user_assigned_identity_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_snapshot_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/recordings/test_elastic_san_volume_group_and_volume_scenarios.yaml
  src/elastic-san/azext_elastic_san/tests/latest/test_elastic_san.py
  src/elastic-san/setup.py
Labels: preview

#8161 Removing msrestazure dependency and using azure.mgmt.core for traffic-collector
  src/traffic-collector/HISTORY.rst
  src/traffic-collector/azext_traffic_collector/custom.py
  src/traffic-collector/setup.py
Labels: customer-reported

#8170 {AKS} Fix test `test_aks_create_and_update_with_http_proxy_config`
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
Labels: AKS, Auto-Assign

#8169 [aks-preview] Fix bug related to updating DCR when non monitoring add enabled through az aks enable-addons
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_helpers.py
  src/aks-preview/azext_aks_preview/addonconfiguration.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#8176 Add Secret Scan to PR CI
  azure-pipelines.yml
Labels: CI, Auto-Assign

#8182 Upgrading MDP extension to stable version 2024-10-19
  src/mdp/HISTORY.rst
  src/mdp/azext_mdp/aaz/latest/mdp/__cmd_group.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/__cmd_group.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_create.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_delete.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_list.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_show.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_update.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_wait.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/agent/__cmd_group.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/agent/_list.py
  src/mdp/azext_mdp/aaz/latest/mdp/sku/__cmd_group.py
  src/mdp/azext_mdp/aaz/latest/mdp/sku/_list.py
  src/mdp/azext_mdp/azext_metadata.json
  src/mdp/azext_mdp/tests/latest/recordings/test_mdp_create_error_scenario.yaml
  src/mdp/azext_mdp/tests/latest/recordings/test_mdp_scenario.yaml
  src/mdp/azext_mdp/tests/latest/recordings/test_mdp_sku_scenario.yaml
  src/mdp/azext_mdp/tests/latest/test_mdp.py
  src/mdp/setup.py
Labels: stable

#8184 [k8s-configuration] Update extension CLI to v2.1.0
  .github/CODEOWNERS
  src/k8s-configuration/HISTORY.rst
  src/k8s-configuration/azext_k8s_configuration/_help.py
  src/k8s-configuration/azext_k8s_configuration/_params.py
  src/k8s-configuration/azext_k8s_configuration/action.py
  src/k8s-configuration/azext_k8s_configuration/consts.py
  src/k8s-configuration/azext_k8s_configuration/providers/FluxConfigurationProvider.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/_source_control_configuration_client.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/models.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/_configuration.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/_source_control_configuration_client.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/_vendor.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/_version.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/_configuration.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/_source_control_configuration_client.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/operations/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/operations/_flux_config_operation_status_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/operations/_flux_configurations_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/aio/operations/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/models/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/models/_models_py3.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/models/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/models/_source_control_configuration_client_enums.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/operations/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/operations/_flux_config_operation_status_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/operations/_flux_configurations_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_04_01_preview/operations/_patch.py
  src/k8s-configuration/setup.py
Labels: Auto-Assign

#8051 Release redisenterprise 1.2.1b1
  src/redisenterprise/HISTORY.rst
  src/redisenterprise/azext_redisenterprise/azext_metadata.json
  src/redisenterprise/setup.py
Labels: preview

#8185 [Containerapp] Release version `1.0.0b4`
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_addon_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_add_on_binding_customized_keys_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_add_on_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_dev_add_on_binding_none_client_type.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_java_component.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_managed_service_binding_e2e.yaml
  src/containerapp/setup.py
Labels: Auto-Assign, ContainerApp

#8010 {CI} Replace deprecated `assertRaisesRegexp` and `assertEquals`
  src/account/azext_account/tests/latest/test_account_scenario.py
  src/apic-extension/azext_apic_extension/tests/latest/test_definition_commands.py
  src/authV2/azext_authV2/tests/latest/test_authV2_scenario.py
  src/automation/azext_automation/tests/latest/test_automation_scenario_manual.py
  src/azure-firewall/azext_firewall/tests/latest/test_azure_firewall_scenario.py
  src/connectedk8s/azext_connectedk8s/tests/latest/test_connectedk8s_scenario.py
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_patch.py
  src/hpc-cache/azext_hpc_cache/tests/latest/test_hpc_cache_scenario.py
  src/network-analytics/azext_network_analytics/tests/latest/test_network_analytics.py
  src/networkcloud/azext_networkcloud/tests/unit/test_custom_managedidentity.py
  src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py
  src/scheduled-query/azext_scheduled_query/tests/latest/test_scheduled_query_scenario.py
  src/spring-cloud/azext_spring_cloud/tests/latest/app_managed_identity/test_app_managed_identity_force_set_scenario.py
  src/spring-cloud/azext_spring_cloud/tests/latest/app_managed_identity/test_app_managed_identity_force_set_validator.py
  src/spring-cloud/azext_spring_cloud/tests/latest/app_managed_identity/test_create_app_with_both_identity_scenario.py
  src/spring-cloud/azext_spring_cloud/tests/latest/app_managed_identity/test_create_app_with_managed_identity_validator.py
  src/spring-cloud/azext_spring_cloud/tests/latest/app_managed_identity/test_create_app_with_user_identity_scenario.py
  src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app.py
  src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app_insights_scenario.py
  src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_app_scenario.py
  src/spring-cloud/azext_spring_cloud/tests/latest/test_asc_scenario.py
  src/spring/azext_spring/tests/latest/app_managed_identity/test_app_managed_identity_force_set_scenario.py
  src/spring/azext_spring/tests/latest/app_managed_identity/test_app_managed_identity_force_set_validator.py
  src/spring/azext_spring/tests/latest/app_managed_identity/test_create_app_with_both_identity_scenario.py
  src/spring/azext_spring/tests/latest/app_managed_identity/test_create_app_with_managed_identity_validator.py
  src/spring/azext_spring/tests/latest/app_managed_identity/test_create_app_with_user_identity_scenario.py
  src/spring/azext_spring/tests/latest/application_configuration_service/test_acs_validators.py
  src/spring/azext_spring/tests/latest/jobs/test_asa_job_deploy_scenario.py
  src/spring/azext_spring/tests/latest/jobs/test_asa_job_execution_instance.py
  src/spring/azext_spring/tests/latest/jobs/test_asa_job_log_stream_validators.py
  src/spring/azext_spring/tests/latest/jobs/test_asa_job_scenario.py
  src/spring/azext_spring/tests/latest/jobs/test_asa_jobs.py
  src/spring/azext_spring/tests/latest/log_stream/test_log_stream_validators.py
  src/spring/azext_spring/tests/latest/managed_component/test_managed_component_validators.py
  src/spring/azext_spring/tests/latest/managed_component/test_writer.py
  src/spring/azext_spring/tests/latest/test_asa_app.py
  src/spring/azext_spring/tests/latest/test_asa_app_insights_scenario.py
  src/spring/azext_spring/tests/latest/test_asa_app_scenario.py
  src/spring/azext_spring/tests/latest/test_asa_application_configuration_service.py
  src/ssh/azext_ssh/tests/latest/test_connectivity_utils.py
Labels: CI, Auto-Assign

#8116 {CI} Update pipeline to use Python 3.12
  azure-pipelines.yml
Labels: CI, Auto-Assign

#8199 Added an error message for incorrect formats of inline attachments in email communication service send email.
  src/communication/HISTORY.rst
  src/communication/azext_communication/manual/custom.py
  src/communication/azext_communication/version.py
Labels: customer-reported

#8178 AKS: Get VM SKU details from backend for validation for Azure Container Storage
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#8218 [connectedk8s] Update extension cli to v1.10.1
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_constants.py
  src/connectedk8s/azext_connectedk8s/_precheckutils.py
  src/connectedk8s/azext_connectedk8s/_utils.py
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#8204 [Containerapp] `az containerapp create`: Fix Role assignment error when the default Azure Container Registry could not be found
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/containerapp_decorator.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_identity_registry.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_managed_service_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_private_registry_port.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_acr_look_up_credentical.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_identity_system.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_registry_identity_user.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Labels: Auto-Assign, ContainerApp
