Repository Azure/azure-cli-extensions, pull requests merged in 2024-01, with the labels that each got.

#7123 {AKS} Fix azdev style issues for decorators
  src/aks-preview/azext_aks_preview/addonconfiguration.py
  src/aks-preview/azext_aks_preview/agentpool_decorator.py
  src/aks-preview/azext_aks_preview/maintenanceconfiguration.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#7144 fix: quantum extension - obfuscating E2E test recordings
  src/quantum/tests.live/Run.ps1
Labels: Quantum, Auto-Assign

#7122 {AKS} Fix azdev style issues for command & custom
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
Labels: AKS, Auto-Assign

#7113 [az vm repair] version 1.0.0b1
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/custom.py
  src/vm-repair/azext_vm_repair/scripts/win-run-driver.ps1
  src/vm-repair/azext_vm_repair/tests/latest/test_repair_commands.py
  src/vm-repair/setup.py
Labels: Compute, Auto-Assign

#7154 {CI} Fix check extension name issue
  scripts/ci/azdev_linter_style.py
Labels: CI, Auto-Assign

#7149 [Network-Manager] Fix #7143: `az network manager connect-config create/update`: Fix to allow cross tenant resource id for `--hub`
  src/network-manager/HISTORY.rst
  src/network-manager/azext_network_manager/__init__.py
  src/network-manager/azext_network_manager/_params.py
  src/network-manager/azext_network_manager/action.py
  src/network-manager/azext_network_manager/commands.py
  src/network-manager/azext_network_manager/custom.py
  src/network-manager/azext_network_manager/tests/latest/test_network_scenario.py
  src/network-manager/setup.py
Labels: Network, Auto-Assign

#7152 Fix quantum lint
  src/quantum/azext_quantum/__init__.py
  src/quantum/azext_quantum/_params.py
  src/quantum/azext_quantum/_storage.py
  src/quantum/azext_quantum/commands.py
  src/quantum/azext_quantum/operations/job.py
  src/quantum/azext_quantum/operations/workspace.py
  src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py
  src/quantum/azext_quantum/tests/latest/test_quantum_targets.py
  src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py
  src/quantum/azext_quantum/tests/latest/utils.py
Labels: Quantum, Auto-Assign

#7148 {CI} Add extension versioning doc in pr template
  .github/pull_request_template.md
Labels: CI, Auto-Assign

#7163 {CI} Add permissions block for `Github Action Permission Changes`
  .github/workflows/AddIssueComment.yml
Labels: CI, Auto-Assign

#7168 [IoT] Add IoT Ops Extension v0.2.0b2
  linter_exclusions.yml
  src/index.json
Labels: IoT/CLI, Auto-Assign

#7166 Az Quantum release to 0.21.0
  src/quantum/HISTORY.rst
  src/quantum/azext_quantum/__init__.py
  src/quantum/setup.py
Labels: Quantum, Auto-Assign

#7040 {AKS} `az aks update`: Add `--ip-families` to support updating cluster networking settings
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign

#7167 [Azure Load Testing] Bug fix and adding a parameter in "az load test-run update" command.
  src/load/HISTORY.rst
  src/load/azext_load/data_plane/client_factory.py
  src/load/azext_load/data_plane/load_test_run/custom.py
  src/load/azext_load/data_plane/load_test_run/params.py
  src/load/azext_load/data_plane/utils/utils.py
  src/load/azext_load/tests/latest/constants.py
  src/load/azext_load/tests/latest/preparers.py
  src/load/azext_load/tests/latest/recordings/test_load_app_component.yaml
  src/load/azext_load/tests/latest/recordings/test_load_scenarios.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_app_component.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_create.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_create_with_args.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_delete.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_download_files.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_file.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_list.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_create.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_delete.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_download_files.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_list.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_metrics.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_server_metric.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_show.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_stop.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_update.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_server_metric.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_show.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_update.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_update_with_config.yaml
  src/load/azext_load/tests/latest/test_load.py
  src/load/azext_load/tests/latest/test_load_test.py
  src/load/azext_load/tests/latest/test_load_testrun.py
  src/load/setup.py
Labels: Auto-Assign

#7139 Whitelist Version Check for Non-Stable Release Trains for connectedk8s
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_utils.py
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#7172 remove workspace commands
  src/apic-extension/HISTORY.rst
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/__cmd_group.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/__init__.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/_create.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/_delete.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/_head.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/_list.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/_show.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/workspace/_update.py
  src/apic-extension/setup.py
Labels: customer-reported

#7176 {AKS} update trustedaccess live test
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_trustedaccess_rolebinding.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_trustedaccess_rolebinding.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7185 [Azure Load Testing] Updating ARM endpoint based on cloud
  src/load/HISTORY.rst
  src/load/azext_load/data_plane/utils/utils.py
  src/load/setup.py
Labels: Auto-Assign

#7140 Add cli changes for windows GPU feature
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/agentpool_decorator.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_skip_gpu_driver_install.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7146 [containerapp] az containerapp add-on create: Support for weaviate add-on
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_addon_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_get_customdomainverificationid_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_on_arc_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Labels: customer-reported

#7193 {AKS} Fix some test cases
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_premium_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_premium_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_vms_agentpool_type.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7191 {AKS} deprecate TA command --source-resource-id alias -r
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_trustedaccess_rolebinding.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7196 [containerapp] az containerapp add-on create: Support for milvus add-on
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_addon_binding_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Labels: customer-reported, Auto-Assign, ContainerApp

#7203 Link HCRP (Arc for servers) machine to vCenter
  src/connectedvmware/HISTORY.rst
  src/connectedvmware/azext_connectedvmware/_actions.py
  src/connectedvmware/azext_connectedvmware/_help.py
  src/connectedvmware/azext_connectedvmware/_params.py
  src/connectedvmware/azext_connectedvmware/_validators.py
  src/connectedvmware/azext_connectedvmware/custom.py
  src/connectedvmware/azext_connectedvmware/tests/latest/test_connectedvmware_scenario.py
  src/connectedvmware/setup.py
Labels: Auto-Assign

#7145 change the table columns to include ipv4,ipv6
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_format.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_machine_cmds.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/setup.py
Labels: customer-reported

#7204 [k8s-extension] Update extension CLI to v1.6.0
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/DataProtectionKubernetes.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/WorkloadIAM.py
  src/k8s-extension/azext_k8s_extension/tests/latest/test_workload_iam.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#7212 [IoT] Add IoT Operations CLI extension v0.2.0b4
  src/index.json
Labels: IoT/CLI, Auto-Assign

#7062 fix: datafactory data-flow update does not work
  src/datafactory/HISTORY.rst
  src/datafactory/azext_datafactory/manual/custom.py
  src/datafactory/setup.py
Labels: customer-reported

#7079 [k8s-runtime] Add `k8s-runtime` extension
  .github/CODEOWNERS
  src/k8s-runtime/HISTORY.rst
  src/k8s-runtime/README.md
  src/k8s-runtime/azext_k8s_runtime/__init__.py
  src/k8s-runtime/azext_k8s_runtime/_help.py
  src/k8s-runtime/azext_k8s_runtime/_params.py
  src/k8s-runtime/azext_k8s_runtime/aaz/__init__.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/__init__.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/__cmd_group.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/__init__.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/__cmd_group.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/__init__.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/_create.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/_delete.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/_list.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/_show.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/_wait.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/__cmd_group.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/__init__.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/_create.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/_delete.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/_list.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/_show.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/_wait.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/service/__cmd_group.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/service/__init__.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/service/_create.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/service/_delete.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/service/_list.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/service/_show.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/__cmd_group.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/__init__.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_create.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_delete.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_list.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_show.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_update.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_wait.py
  src/k8s-runtime/azext_k8s_runtime/azext_metadata.json
  src/k8s-runtime/azext_k8s_runtime/commands.py
  src/k8s-runtime/azext_k8s_runtime/custom.py
  src/k8s-runtime/azext_k8s_runtime/custom_commands/__init__.py
  src/k8s-runtime/azext_k8s_runtime/custom_commands/common.py
  src/k8s-runtime/azext_k8s_runtime/custom_commands/load_balancer.py
  src/k8s-runtime/azext_k8s_runtime/custom_commands/storage_class.py
  src/k8s-runtime/azext_k8s_runtime/tests/__init__.py
  src/k8s-runtime/azext_k8s_runtime/tests/latest/__init__.py
  src/k8s-runtime/azext_k8s_runtime/tests/latest/recordings/test_load_balancer_enable_disable.yaml
  src/k8s-runtime/azext_k8s_runtime/tests/latest/recordings/test_storage_class_enable_disable.yaml
  src/k8s-runtime/azext_k8s_runtime/tests/latest/test_k8s_runtime.py
  src/k8s-runtime/setup.cfg
  src/k8s-runtime/setup.py
  src/service_name.json
Labels: Auto-Assign

#7147 {AKS} Update AKS live test matrix
  src/aks-preview/azcli_aks_live_test/configs/cli_matrix_default.json
  src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
Labels: AKS, Auto-Assign

#7202 {ServiceConnector}: support function app in Service Connector passwordless
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_resource_config.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_utils.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/action.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/azext_metadata.json
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/tests/__init__.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/tests/latest/__init__.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/tests/latest/test_serviceconnector-passwordless_scenario.py
  src/serviceconnector-passwordless/setup.py
Labels: Functions, Auto-Assign

#7225 [Service Connector] release version and make some improvement
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_utils.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#7208 {CI} Add module release version calulation workflow
  .github/workflows/VersionCalPRComment.yml
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#7231 Refactor azure service mesh update function for better readability
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign
