Repository Azure/azure-cli-extensions, pull requests merged in 2024-07, with the labels that each got.

#7758 {Service Connector}: fix postgresql connection string format
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
Labels: Auto-Assign

#7728 Communication chat test scenario remove participant - updated the error code in comment
  src/communication/azext_communication/tests/latest/test_communication_chat_scenario.py
Labels: customer-reported, skip-cal-version

#7716 Dashboard sync library panel version mismatch bug fix
  src/amg/HISTORY.rst
  src/amg/azext_amg/sync.py
  src/amg/azext_amg/tests/latest/recordings/test_amg_backup_restore.yaml
  src/amg/azext_amg/utils.py
  src/amg/setup.py
Labels: extension/grafana, Auto-Assign

#7759 {CI} Update parse gh label json string
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#7763 [connectedvmware] Search for BIOS IDs with both Big Endian and Middle Endian
  src/connectedvmware/HISTORY.rst
  src/connectedvmware/azext_connectedvmware/custom.py
  src/connectedvmware/setup.py
Labels: Auto-Assign

#7755 AKS: Add and fix additional validations to ephemeral disk operation
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
Labels: AKS, Auto-Assign

#7767 {Service Connector} bump version
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#7775 {AKS} Fix several cases broken by network module bumping API
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_pod_ip_allocation_mode_static_block.yaml
Labels: AKS, Network, Auto-Assign

#7769 Feature accessrule servicetag changes
  src/nsp/HISTORY.rst
  src/nsp/azext_nsp/aaz/latest/network/perimeter/_create.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/_list.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/_show.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/association/_create.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/association/_list.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/association/_show.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/association/_update.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/association/_wait.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link/_create.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link/_list.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link/_show.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link/_update.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link/_wait.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link_reference/_list.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link_reference/_show.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/link_reference/_wait.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/onboarded_resources/_list.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/profile/_create.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/profile/_list.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/profile/_show.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/profile/access_rule/_create.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/profile/access_rule/_list.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/profile/access_rule/_show.py
  src/nsp/azext_nsp/aaz/latest/network/perimeter/profile/access_rule/_update.py
  src/nsp/azext_nsp/azext_metadata.json
  src/nsp/azext_nsp/tests/latest/test_nsp.py
  src/nsp/setup.py
Labels: release-version-block

#7782 [aks] Change aks draft up Summary
  src/aks-preview/azext_aks_preview/_help.py
Labels: AKS, Auto-Assign

#7790 [AKS]: Remove support for `az aks mesh` egress gateway commands
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_egress_gateway.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7795 [Storage-Preview] `az storage account local-user`: Add ACL support, and list paging/filtering
  src/storage-preview/HISTORY.rst
  src/storage-preview/azext_storage_preview/_help.py
  src/storage-preview/azext_storage_preview/_params.py
  src/storage-preview/azext_storage_preview/_validators.py
  src/storage-preview/azext_storage_preview/commands.py
  src/storage-preview/azext_storage_preview/operations/account.py
  src/storage-preview/azext_storage_preview/tests/latest/recordings/test_storage_account_local_user.yaml
  src/storage-preview/azext_storage_preview/tests/latest/test_storage_account_scenarios.py
Labels: Storage, Auto-Assign

#7789 {AKS} Switch to use shared user assigned identity to run managed live test
  src/aks-preview/azcli_aks_live_test/scripts/transcribe_env.sh
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7729 Remove redundant aad login commands from example section
  src/bastion/HISTORY.rst
  src/bastion/azext_bastion/_help.py
  src/bastion/azext_bastion/tests/latest/recordings/test_bastion_host_crud.yaml
  src/bastion/setup.py
Labels: customer-reported

#7792 sync auto-generated codes with aaz codegen
  src/acat/azext_acat/aaz/latest/acat/__cmd_group.py
  src/acat/azext_acat/aaz/latest/acat/_onboard.py
  src/acat/azext_acat/aaz/latest/acat/report/__cmd_group.py
  src/acat/azext_acat/aaz/latest/acat/report/_create.py
  src/acat/azext_acat/aaz/latest/acat/report/_delete.py
  src/acat/azext_acat/aaz/latest/acat/report/_update.py
  src/acat/azext_acat/aaz/latest/acat/report/snapshot/_list.py
  src/acat/azext_acat/aaz/latest/acat/report/webhook/_create.py
  src/acat/azext_acat/aaz/latest/acat/report/webhook/_update.py
  src/acat/azext_acat/custom.py
  src/acat/azext_acat/tests/latest/recordings/test_create_report.yaml
  src/acat/azext_acat/tests/latest/recordings/test_create_webhook.yaml
  src/acat/azext_acat/tests/latest/recordings/test_delete_report.yaml
  src/acat/azext_acat/tests/latest/recordings/test_delete_webhook.yaml
  src/acat/azext_acat/tests/latest/recordings/test_download_report.yaml
  src/acat/azext_acat/tests/latest/recordings/test_get_control_assessments.yaml
  src/acat/azext_acat/tests/latest/recordings/test_get_control_assessments_no_snapshot.yaml
  src/acat/azext_acat/tests/latest/recordings/test_list_report.yaml
  src/acat/azext_acat/tests/latest/recordings/test_quick_evaluation.yaml
  src/acat/azext_acat/tests/latest/recordings/test_update_report.yaml
  src/acat/azext_acat/tests/latest/recordings/test_update_webhook.yaml
  src/acat/azext_acat/tests/latest/test_acat_report.py
Labels: Code Gen, Auto-Assign

#7805 {AKS} fix error message of `az aks nodepool manual-scale update`
  src/aks-preview/azext_aks_preview/custom.py
Labels: AKS, Auto-Assign

#7801 [AKS] Remove support for az aks get-os-options command
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7806 {AKS} Update the minimum required cli core version to `2.61.0`.
  src/aks-preview/HISTORY.rst
  src/aks-preview/README.rst
  src/aks-preview/azext_aks_preview/azext_metadata.json
Labels: AKS, Auto-Assign

#7813 Speficy network plugin in test
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: Network, Auto-Assign

#7817 [AKS] Support IMDS restriction
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_enable_imds_restriction.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/linter_exclusions.yml
Labels: AKS, Auto-Assign

#7812 {service connector}update postgresql permission
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#7823 AKS: Add validation for PremiumV2 disks and fixes in error messages
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7818 {CI} Add non-security issue label check
  .github/template/non-security-comment.md
  .github/workflows/AddIssueCommentWithLabel.yml
Labels: CI, Auto-Assign

#7831 package HISTORY.rst
  src/connectedk8s/MANIFEST.in
Labels: Connected Kubernetes, Auto-Assign

#7830 [dataprotection] Add support for MUA for dataprotection policy update
  src/dataprotection/HISTORY.rst
  src/dataprotection/azext_dataprotection/manual/_params.py
  src/dataprotection/azext_dataprotection/manual/aaz_operations/backup_instance.py
  src/dataprotection/azext_dataprotection/manual/custom.py
  src/dataprotection/azext_dataprotection/manual/helpers.py
  src/dataprotection/azext_dataprotection/tests/latest/recordings/test_dataprotection_backup_instance_create_and_delete_blob.yaml
  src/dataprotection/azext_dataprotection/tests/latest/recordings/test_dataprotection_backup_instance_create_backup_delete_disk.yaml
  src/dataprotection/setup.py
Labels: Data Protection, Auto-Assign, release-version-block

#7819 Update usage of deprecated folder & dashboard endpoints
  src/amg/HISTORY.rst
  src/amg/azext_amg/_params.py
  src/amg/azext_amg/custom.py
  src/amg/azext_amg/tests/latest/recordings/test_amg_backup_restore.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_crud.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_api_key_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_service_account_e2e.yaml
  src/amg/setup.py
Labels: extension/grafana, Auto-Assign

#7810 Upgrade ArcK8sDiagnoser and fix Style, Linter issues
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/_client_factory.py
  src/connectedk8s/azext_connectedk8s/_clientproxyutils.py
  src/connectedk8s/azext_connectedk8s/_constants.py
  src/connectedk8s/azext_connectedk8s/_precheckutils.py
  src/connectedk8s/azext_connectedk8s/_troubleshootutils.py
  src/connectedk8s/azext_connectedk8s/_utils.py
  src/connectedk8s/azext_connectedk8s/_validators.py
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign

#7836 {CI} Adjust version cal job structure
  .github/workflows/VersionCalPRComment.yml
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#7778 [SCVMM] Add support for latest API version
  src/scvmm/HISTORY.rst
  src/scvmm/azext_scvmm/_client_factory.py
  src/scvmm/azext_scvmm/custom.py
  src/scvmm/azext_scvmm/scvmm_constants.py
  src/scvmm/azext_scvmm/tests/latest/recordings/test_scvmm.yaml
  src/scvmm/azext_scvmm/tests/latest/test_scvmm_scenario.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/__init__.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/_configuration.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/_sc_vmm_mgmt_client.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/__init__.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/_configuration.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/_sc_vmm_mgmt_client.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/__init__.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_availability_sets_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_clouds_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_guest_agents_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_inventory_items_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_virtual_machine_instances_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_virtual_machine_templates_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_virtual_networks_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_vm_instance_hybrid_identity_metadatas_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/aio/operations/_vmm_servers_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/models/__init__.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/models/_models.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/models/_models_py3.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/models/_sc_vmm_mgmt_client_enums.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/__init__.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_availability_sets_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_clouds_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_guest_agents_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_inventory_items_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_virtual_machine_instances_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_virtual_machine_templates_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_virtual_networks_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_vm_instance_hybrid_identity_metadatas_operations.py
  src/scvmm/azext_scvmm/vendored_sdks/scvmm/operations/_vmm_servers_operations.py
  src/scvmm/setup.py
Labels: skip-cal-version
