Repository Azure/azure-cli-extensions, pull requests merged in 2024-03, with the labels that each got.

#7332 {CI} Disable Credential Scanner
  azure-pipelines.yml
Labels: CI, Auto-Assign

#7312 Fixing payload for failureCriteria and updated test recordings
  src/load/HISTORY.rst
  src/load/azext_load/data_plane/utils/utils.py
  src/load/azext_load/tests/latest/recordings/test_load_app_component.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_app_component.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_create.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_create_with_args.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_delete.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_download_files.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_file.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_list.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_create.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_delete.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_download_files.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_list.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_metrics.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_server_metric.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_show.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_stop.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_run_update.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_server_metric.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_show.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_update.yaml
  src/load/azext_load/tests/latest/recordings/test_load_test_update_with_config.yaml
  src/load/setup.py
Labels: Auto-Assign, auto-cal-version

#7330 {AKS} Update tests for ASM egress gateway to allow for BadRequest response
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7335 {containerapp} remove additional conversion of binding name of Java component
  src/containerapp/azext_containerapp/_constants.py
  src/containerapp/azext_containerapp/_utils.py
  src/containerapp/azext_containerapp/containerapp_decorator.py
  src/containerapp/azext_containerapp/java_component_decorator.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_java_component.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_java_component.py
Labels: Auto-Assign, ContainerApp

#7336 [Container app] Bump version 0.3.48
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_max_inactive_revisions.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
  src/containerapp/setup.py
Labels: Auto-Assign, ContainerApp

#7324 fix: quantum extension elements test
  src/quantum/azext_quantum/tests/latest/recordings/test_get_provider.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_jobs.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_submit.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_targets.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_version_check.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_workspace.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_workspace_create_destroy.yaml
  src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py
Labels: Quantum, Auto-Assign

#7309 AMG: Backup & restore provision dashboard bug fix
  src/amg/HISTORY.rst
  src/amg/azext_amg/backup.py
  src/amg/azext_amg/custom.py
  src/amg/azext_amg/restore.py
  src/amg/azext_amg/tests/__init__.py
  src/amg/azext_amg/tests/latest/__init__.py
  src/amg/azext_amg/tests/latest/recordings/test_amg_backup_restore.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_crud.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_api_key_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_service_account_e2e.yaml
  src/amg/azext_amg/tests/latest/test_amg_scenario.py
  src/amg/azext_amg/tests/latest/test_definitions.py
  src/amg/setup.py
Labels: extension/grafana, Auto-Assign, auto-cal-version

#7287 [Quantum]Add Azure quantum api key support
  src/quantum/HISTORY.rst
  src/quantum/azext_quantum/__init__.py
  src/quantum/azext_quantum/_client_factory.py
  src/quantum/azext_quantum/_help.py
  src/quantum/azext_quantum/_params.py
  src/quantum/azext_quantum/commands.py
  src/quantum/azext_quantum/operations/job.py
  src/quantum/azext_quantum/operations/workspace.py
  src/quantum/azext_quantum/tests/latest/recordings/test_job_errors.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_jobs.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_offerings_errors.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_submit.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_submit_dft.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_targets.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_version_check.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_workspace.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_workspace_create_destroy.yaml
  src/quantum/azext_quantum/tests/latest/recordings/test_workspace_keys.yaml
  src/quantum/azext_quantum/tests/latest/test_quantum_workspace.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/__init__.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/_azure_quantum_management_client.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/_client.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/_configuration.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/_patch.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/_serialization.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/_vendor.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/__init__.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/_client.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/_configuration.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/_patch.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/operations/__init__.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/operations/_offerings_operations.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/operations/_operations.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/operations/_patch.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/operations/_workspace_operations.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/aio/operations/_workspaces_operations.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/models/__init__.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/models/_enums.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/models/_models.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/models/_models_py3.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/models/_patch.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/operations/__init__.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/operations/_offerings_operations.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/operations/_operations.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/operations/_patch.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/operations/_workspace_operations.py
  src/quantum/azext_quantum/vendored_sdks/azure_mgmt_quantum/operations/_workspaces_operations.py
  src/quantum/setup.py
Labels: Quantum, Auto-Assign, auto-cal-version

#7329 [ContainerApp] Set container name for source to cloud builds to the container app name
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/containerapp_decorator.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_source_with_default_registry_image.yaml
  src/containerapp/azext_containerapp/tests/latest/utils.py
Labels: Auto-Assign, ContainerApp

#7303 AMG: add Grafana major version arg to update command
  src/amg/HISTORY.rst
  src/amg/azext_amg/_client_factory.py
  src/amg/azext_amg/_help.py
  src/amg/azext_amg/_params.py
  src/amg/azext_amg/custom.py
  src/amg/azext_amg/tests/latest/recordings/test_amg_backup_restore.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_crud.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_api_key_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_service_account_e2e.yaml
  src/amg/azext_amg/utils.py
  src/amg/azext_amg/vendored_sdks/__init__.py
  src/amg/azext_amg/vendored_sdks/_configuration.py
  src/amg/azext_amg/vendored_sdks/_dashboard_management_client.py
  src/amg/azext_amg/vendored_sdks/_patch.py
  src/amg/azext_amg/vendored_sdks/_serialization.py
  src/amg/azext_amg/vendored_sdks/_vendor.py
  src/amg/azext_amg/vendored_sdks/_version.py
  src/amg/azext_amg/vendored_sdks/aio/__init__.py
  src/amg/azext_amg/vendored_sdks/aio/_configuration.py
  src/amg/azext_amg/vendored_sdks/aio/_dashboard_management_client.py
  src/amg/azext_amg/vendored_sdks/aio/_patch.py
  src/amg/azext_amg/vendored_sdks/aio/operations/__init__.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_enterprise_details_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_grafana_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_patch.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_private_endpoint_connections_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_private_link_resources_operations.py
  src/amg/azext_amg/vendored_sdks/models/__init__.py
  src/amg/azext_amg/vendored_sdks/models/_dashboard_management_client_enums.py
  src/amg/azext_amg/vendored_sdks/models/_models_py3.py
  src/amg/azext_amg/vendored_sdks/models/_patch.py
  src/amg/azext_amg/vendored_sdks/operations/__init__.py
  src/amg/azext_amg/vendored_sdks/operations/_enterprise_details_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_grafana_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_patch.py
  src/amg/azext_amg/vendored_sdks/operations/_private_endpoint_connections_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_private_link_resources_operations.py
  src/amg/azext_amg/vendored_sdks/py.typed
  src/amg/setup.py
Labels: extension/grafana, Auto-Assign

#7342 {ServiceConnector}: Fix user-agent missing and getting postgres db exception
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_client_factory.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#7259 support certificate from keyvault
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/_models.py
  src/containerapp/azext_containerapp/_params.py
  src/containerapp/azext_containerapp/containerapp_env_certificate_decorator.py
  src/containerapp/azext_containerapp/containerapp_env_decorator.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_identity_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_identity_system.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_identity_user.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_msi_certificate.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_msi_certificate_random_name.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_msi_custom_domains.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_commands.py
Labels: Auto-Assign

#7247 NGINX.NGINXPLUS 1.0.0
  src/nginx/HISTORY.rst
  src/nginx/azext_nginx/__init__.py
  src/nginx/azext_nginx/_params.py
  src/nginx/azext_nginx/aaz/latest/__init__.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/_create.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/_delete.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/_list.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/_show.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/_update.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/_wait.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/certificate/_create.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/certificate/_delete.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/certificate/_list.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/certificate/_show.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/certificate/_update.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/certificate/_wait.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/__init__.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/_analyze.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/_create.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/_delete.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/_list.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/_show.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/_update.py
  src/nginx/azext_nginx/aaz/latest/nginx/deployment/configuration/_wait.py
  src/nginx/azext_nginx/azext_metadata.json
  src/nginx/azext_nginx/tests/latest/recordings/test_deployment_cert_config.yaml
  src/nginx/azext_nginx/tests/latest/test_nginx_scenario.py
  src/nginx/setup.py
Labels: customer-reported

#7353 {AKS} `az aks mesh get-upgrades` fails with a traceback if ASM addon is disabled
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7361 [IoT] Adds IoT Operations Extension v0.4.0b1
  src/index.json
Labels: IoT/CLI, Auto-Assign

#7358 [Container app] Release version 0.3.49
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_managed_service_binding_e2e.yaml
  src/containerapp/setup.py
Labels: Auto-Assign, ContainerApp

#7355 [CI] Add version cal workflow
  .github/workflows/VersionCalPRComment.yml
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#7243 [AKS] Add Trusted Launch Preview CLI flags
  src/aks-preview/HISTORY.rst
  src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/agentpool_decorator.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_update_secure_boot_flow.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_update_vtpm_flow.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7369 {AKS} Fix recording file for case `test_aks_approuting_enable_with_keyvault_secrets_provider_addon_and_keyvault_id`
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_approuting_enable_with_keyvault_secrets_provider_addon_and_keyvault_id.yaml
Labels: AKS, Auto-Assign, auto-cal-version

#7363 AMG: Update azure-mgmt-authorization package version
  src/amg/HISTORY.rst
  src/amg/azext_amg/custom.py
  src/amg/azext_amg/tests/latest/recordings/test_amg_backup_restore.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_crud.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_api_key_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_service_account_e2e.yaml
  src/amg/azext_amg/utils.py
  src/amg/setup.py
Labels: extension/grafana, Auto-Assign, auto-cal-version

#7368 Change default ACS generation to Gen2
  src/spring/HISTORY.md
  src/spring/azext_spring/_tanzu_component.py
  src/spring/azext_spring/tests/latest/test_asa_create.py
  src/spring/setup.py
Labels: AKS, Auto-Assign, auto-cal-version

#7381 Add ML extension 2.24.0
  src/index.json
Labels: extension/ml, Machine Learning, Auto-Assign

#7370 [Blockchain] Deprecate blockchain extension
  .github/CODEOWNERS
  linter_exclusions.yml
  src/blockchain/HISTORY.rst
  src/blockchain/README.md
  src/blockchain/azext_blockchain/__init__.py
  src/blockchain/azext_blockchain/action.py
  src/blockchain/azext_blockchain/azext_metadata.json
  src/blockchain/azext_blockchain/custom.py
  src/blockchain/azext_blockchain/generated/__init__.py
  src/blockchain/azext_blockchain/generated/_client_factory.py
  src/blockchain/azext_blockchain/generated/_help.py
  src/blockchain/azext_blockchain/generated/_params.py
  src/blockchain/azext_blockchain/generated/_validators.py
  src/blockchain/azext_blockchain/generated/action.py
  src/blockchain/azext_blockchain/generated/commands.py
  src/blockchain/azext_blockchain/generated/custom.py
  src/blockchain/azext_blockchain/manual/__init__.py
  src/blockchain/azext_blockchain/manual/_help.py
  src/blockchain/azext_blockchain/tests/__init__.py
  src/blockchain/azext_blockchain/tests/latest/__init__.py
  src/blockchain/azext_blockchain/tests/latest/preparers.py
  src/blockchain/azext_blockchain/tests/latest/recordings/test_blockchain.yaml
  src/blockchain/azext_blockchain/tests/latest/test_blockchain_scenario.py
  src/blockchain/azext_blockchain/vendored_sdks/__init__.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/__init__.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/_blockchain_management_client.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/_configuration.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/_version.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/__init__.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/_blockchain_management_client_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/_configuration_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/operations_async/__init__.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/operations_async/_blockchain_member_operation_result_operations_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/operations_async/_blockchain_member_operations_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/operations_async/_location_operations_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/operations_async/_operation_operations_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/operations_async/_sku_operations_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/aio/operations_async/_transaction_node_operations_async.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/models/__init__.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/models/_blockchain_management_client_enums.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/models/_models.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/models/_models_py3.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/operations/__init__.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/operations/_blockchain_member_operation_result_operations.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/operations/_blockchain_member_operations.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/operations/_location_operations.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/operations/_operation_operations.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/operations/_sku_operations.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/operations/_transaction_node_operations.py
  src/blockchain/azext_blockchain/vendored_sdks/blockchain/py.typed
  src/blockchain/report.md
  src/blockchain/setup.cfg
  src/blockchain/setup.py
  src/index.json
  src/service_name.json
Labels: auto-cal-version

#7384 [CI] Add upstream branch name prefix to avoid conflict in version cal
  .github/workflows/VersionCalPRComment.yml
Labels: CI, Auto-Assign

#7215 AKS: Add changes for resource consumption for Azure Container Storage
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_consts.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_validators.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7386 AKS: Fix the resource allocated after disabling Azure Container Storage for "all" option in ephemeralDisk storagepool type.
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign, auto-cal-version

#7389 [az fleet] Bumping fleet SDK to latest preview version
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/__init__.py
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubful.yaml
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubless.yaml
  src/fleet/azext_fleet/vendored_sdks/_configuration.py
  src/fleet/azext_fleet/vendored_sdks/_container_service_fleet_mgmt_client.py
  src/fleet/azext_fleet/vendored_sdks/_serialization.py
  src/fleet/azext_fleet/vendored_sdks/_version.py
  src/fleet/azext_fleet/vendored_sdks/aio/_configuration.py
  src/fleet/azext_fleet/vendored_sdks/aio/_container_service_fleet_mgmt_client.py
  src/fleet/azext_fleet/vendored_sdks/models.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/__init__.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/_configuration.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/_container_service_fleet_mgmt_client.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/_patch.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/_vendor.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/_version.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/__init__.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/_configuration.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/_container_service_fleet_mgmt_client.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/_patch.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/operations/__init__.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/operations/_fleet_members_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/operations/_fleet_update_strategies_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/operations/_fleets_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/operations/_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/operations/_patch.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/aio/operations/_update_runs_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/models/__init__.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/models/_container_service_fleet_mgmt_client_enums.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/models/_models_py3.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/models/_patch.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/operations/__init__.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/operations/_fleet_members_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/operations/_fleet_update_strategies_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/operations/_fleets_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/operations/_operations.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/operations/_patch.py
  src/fleet/azext_fleet/vendored_sdks/v2024_02_02_preview/operations/_update_runs_operations.py
  src/fleet/setup.py
Labels: Auto-Assign

#7365 feat: remove portal commands from apic-extension
  src/apic-extension/HISTORY.rst
  src/apic-extension/azext_apic_extension/aaz/latest/__init__.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/__cmd_group.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/__init__.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/default/__cmd_group.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/default/__init__.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/default/_create.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/default/_delete.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/default/_show.py
  src/apic-extension/azext_apic_extension/aaz/latest/apic/service/portal/default/_update.py
Labels: auto-cal-version

#7371 Change Login Migration Console App source to NuGet.org and Versioning…
  src/datamigration/HISTORY.rst
  src/datamigration/azext_datamigration/azext_metadata.json
  src/datamigration/azext_datamigration/manual/custom.py
  src/datamigration/azext_datamigration/manual/helper.py
  src/datamigration/setup.py
Labels: Data Migration, Auto-Assign, auto-cal-version

#7230 {AKS} Support reset default value for loadbalancer profile and natgateway profile
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_loadbalancer.py
  src/aks-preview/azext_aks_preview/_natgateway.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_outbound_ips.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py
  src/aks-preview/azext_aks_preview/tests/latest/test_natgateway.py
Labels: AKS, Auto-Assign

#7296 [Spring] Show ACS configs
  src/spring/HISTORY.md
  src/spring/azext_spring/_help.py
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/_utils.py
  src/spring/azext_spring/_validators_enterprise.py
  src/spring/azext_spring/application_configuration_service.py
  src/spring/azext_spring/commands.py
  src/spring/azext_spring/tests/latest/application_configuration_service/__init__.py
  src/spring/azext_spring/tests/latest/application_configuration_service/test_acs_validators.py
  src/spring/setup.py
Labels: AKS, Auto-Assign

#7356 [Containerapp] az containerapp env telemetry: add command for CRUD otlp settings
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/_params.py
  src/containerapp/azext_containerapp/_transformers.py
  src/containerapp/azext_containerapp/_validators.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/containerapp_env_telemetry_decorator.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_telemetry_app_insights_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_telemetry_data_dog_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_telemetry_otlp_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_telemetry.py
Labels: Auto-Assign, ContainerApp, auto-cal-version

#7410 {CI} Fix index.json
  src/index.json
Labels: CI, Auto-Assign

#7393 adding version 1.1.2
  src/index.json
Labels: auto-cal-version

#6986 {application-insights} Add connection string into app settings
  src/application-insights/HISTORY.rst
  src/application-insights/azext_applicationinsights/custom.py
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_storage.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_linked_workspace.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_component_with_public_network_access.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_function.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_function_cross_resource_groups.yaml
  src/application-insights/azext_applicationinsights/tests/latest/recordings/test_connect_webapp.yaml
  src/application-insights/azext_applicationinsights/tests/latest/test_applicationinsights_mgmt.py
  src/application-insights/setup.py
Labels: auto-cal-version

#7415 [IoT] Adds IoT Operations Extension v0.4.0b3
  src/index.json
Labels: IoT/CLI, Auto-Assign

#7387 [DiagnosticRP]add a new cli extension for spot vm placement score
  src/compute-diagnostic-rp/HISTORY.rst
  src/compute-diagnostic-rp/README.md
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/__init__.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/_help.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/_params.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/aaz/__init__.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/aaz/latest/__init__.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/aaz/latest/compute_diagnostic/__cmd_group.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/aaz/latest/compute_diagnostic/__init__.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/aaz/latest/compute_diagnostic/spot_placement_recommender/__cmd_group.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/aaz/latest/compute_diagnostic/spot_placement_recommender/__init__.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/aaz/latest/compute_diagnostic/spot_placement_recommender/_generate.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/azext_metadata.json
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/commands.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/custom.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/tests/__init__.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/tests/latest/__init__.py
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/tests/latest/recordings/test_spot_placement_recommender_generate.yaml
  src/compute-diagnostic-rp/azext_compute_diagnostic_rp/tests/latest/test_compute_diagnostic_rp.py
  src/compute-diagnostic-rp/setup.cfg
  src/compute-diagnostic-rp/setup.py
  src/service_name.json
Labels: auto-cal-version

#7424 [CI] Fix label quote caused tag parsing bug
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#7419 [ML] chore: Add ml extension 2.25.0
  src/index.json
Labels: extension/ml, Machine Learning, Auto-Assign, auto-cal-version

#7354 Updating batch cli extensions
  src/index.json
Labels: auto-cal-version

#7428 [Container app] Release version 0.3.50
  src/containerapp/HISTORY.rst
  src/containerapp/setup.py
Labels: Auto-Assign, ContainerApp

#7421 AMG: Move azure-mgmt-dashboard to vendored SDK
  src/amg/HISTORY.rst
  src/amg/azext_amg/_client_factory.py
  src/amg/azext_amg/_params.py
  src/amg/azext_amg/custom.py
  src/amg/azext_amg/vendored_sdks/__init__.py
  src/amg/azext_amg/vendored_sdks/_configuration.py
  src/amg/azext_amg/vendored_sdks/_dashboard_management_client.py
  src/amg/azext_amg/vendored_sdks/_patch.py
  src/amg/azext_amg/vendored_sdks/_serialization.py
  src/amg/azext_amg/vendored_sdks/_vendor.py
  src/amg/azext_amg/vendored_sdks/_version.py
  src/amg/azext_amg/vendored_sdks/aio/__init__.py
  src/amg/azext_amg/vendored_sdks/aio/_configuration.py
  src/amg/azext_amg/vendored_sdks/aio/_dashboard_management_client.py
  src/amg/azext_amg/vendored_sdks/aio/_patch.py
  src/amg/azext_amg/vendored_sdks/aio/operations/__init__.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_grafana_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_managed_private_endpoints_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_patch.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_private_endpoint_connections_operations.py
  src/amg/azext_amg/vendored_sdks/aio/operations/_private_link_resources_operations.py
  src/amg/azext_amg/vendored_sdks/models/__init__.py
  src/amg/azext_amg/vendored_sdks/models/_dashboard_management_client_enums.py
  src/amg/azext_amg/vendored_sdks/models/_models_py3.py
  src/amg/azext_amg/vendored_sdks/models/_patch.py
  src/amg/azext_amg/vendored_sdks/operations/__init__.py
  src/amg/azext_amg/vendored_sdks/operations/_grafana_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_managed_private_endpoints_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_patch.py
  src/amg/azext_amg/vendored_sdks/operations/_private_endpoint_connections_operations.py
  src/amg/azext_amg/vendored_sdks/operations/_private_link_resources_operations.py
  src/amg/azext_amg/vendored_sdks/py.typed
  src/amg/setup.py
Labels: auto-cal-version

#7433 {AKS} Fix test cases related premium sku
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_premium_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_premium_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign
