Repository Azure/azure-cli-extensions, pull requests merged in 2024-04, with the labels that each got.

#7391 [az fleet] Added skip command to UpdateRun group.
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/_help.py
  src/fleet/azext_fleet/_helpers.py
  src/fleet/azext_fleet/_params.py
  src/fleet/azext_fleet/_validators.py
  src/fleet/azext_fleet/commands.py
  src/fleet/azext_fleet/custom.py
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubless.yaml
  src/fleet/azext_fleet/tests/latest/test_fleet_hubless_scenario.py
  src/fleet/setup.py
Labels: Auto-Assign, auto-cal-version

#7439 {CI} Use GitHub Actions to trigger the ADO OneBranch Extension Release Pipeline
  .github/workflows/TriggerExtensionRelease.yml
Labels: CI, Auto-Assign, auto-cal-version

#7351 Initial release of managed devops pools
  .github/CODEOWNERS
  src/mdp/HISTORY.rst
  src/mdp/README.md
  src/mdp/azext_mdp/__init__.py
  src/mdp/azext_mdp/_help.py
  src/mdp/azext_mdp/_params.py
  src/mdp/azext_mdp/aaz/__init__.py
  src/mdp/azext_mdp/aaz/latest/__init__.py
  src/mdp/azext_mdp/aaz/latest/mdp/__cmd_group.py
  src/mdp/azext_mdp/aaz/latest/mdp/__init__.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/__cmd_group.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/__init__.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_create.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_delete.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_list.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_show.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_update.py
  src/mdp/azext_mdp/aaz/latest/mdp/pool/_wait.py
  src/mdp/azext_mdp/azext_metadata.json
  src/mdp/azext_mdp/commands.py
  src/mdp/azext_mdp/custom.py
  src/mdp/azext_mdp/tests/__init__.py
  src/mdp/azext_mdp/tests/latest/__init__.py
  src/mdp/azext_mdp/tests/latest/recordings/test_mdp_create_error_scenario.yaml
  src/mdp/azext_mdp/tests/latest/recordings/test_mdp_scenario.yaml
  src/mdp/azext_mdp/tests/latest/test_mdp.py
  src/mdp/setup.cfg
  src/mdp/setup.py
  src/service_name.json
Labels: auto-cal-version

#7443 {CI} Cancel serial release
  .github/workflows/TriggerExtensionRelease.yml
Labels: CI, Auto-Assign

#7280 [AKS] Add a new command to check outbound network from nodes `az aks check-network outbound`
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_helpers.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_check_network.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_helpers.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
Labels: AKS, Auto-Assign, auto-cal-version

#7442 {AKS} Bump the minimum required cli core version to `2.56.0`
  src/aks-preview/HISTORY.rst
  src/aks-preview/README.rst
  src/aks-preview/azext_aks_preview/azext_metadata.json
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7448 {CI} Modify the structure and put azure-cli-extensions and azure-docs-cli at the same level
  scripts/ci/avail-ext-doc/update_extension_list.py
Labels: CI, Auto-Assign

#7438 Remove nodeSelector support for egress gateway for `az aks mesh` command.
  src/aks-preview/HISTORY.rst
  src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_with_egress_gateway.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign, auto-cal-version

#7451 [az fleet] RP now defaults dns_name_prefix, remove az defaulting
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/custom.py
  src/fleet/setup.py
Labels: Auto-Assign, auto-cal-version

#7468 [CI] Limit workflow target branches
  .github/workflows/AddPRComment.yml
  .github/workflows/BlockPRMerge.yml
  .github/workflows/VersionCalPRComment.yml
Labels: CI, Auto-Assign

#7467 Refactor for log streaming validators.
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/_validators.py
  src/spring/azext_spring/log_stream/log_stream_validators.py
  src/spring/azext_spring/managed_components/managed_component_operations.py
  src/spring/azext_spring/managed_components/validators_managed_component.py
  src/spring/azext_spring/tests/latest/log_stream/__init__.py
  src/spring/azext_spring/tests/latest/log_stream/test_log_stream_validators.py
  src/spring/azext_spring/tests/latest/managed_component/test_managed_component_validators.py
Labels: auto-cal-version

#7473 Bump minCliCoreVersion to 2.56.0 for Spring
  src/spring/azext_spring/azext_metadata.json
Labels: auto-cal-version

#7334 {CI} Block PR merge on blocked labels
  .github/workflows/BlockPRMerge.yml
Labels: CI, Auto-Assign

#7455 [ConnectedK8s] Add support for multiple proxy instances running on the same machine using different ports
  src/connectedk8s/HISTORY.rst
  src/connectedk8s/azext_connectedk8s/custom.py
  src/connectedk8s/setup.py
Labels: Connected Kubernetes, Auto-Assign, auto-cal-version

#7435 feat: Support shared slb probe
  linter_exclusions.yml
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_loadbalancer.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_or_update_with_health_probe_mode.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer.py
Labels: AKS, Auto-Assign, auto-cal-version

#7463 remove comment
  src/containerapp/azext_containerapp/_cloud_build_utils.py
Labels: auto-cal-version

#7466 Rename spring cloud config to config server for spring, rename spring…
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_help.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/custom.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_java_component.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_java_component_deprecated.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_java_component.py
Labels: auto-cal-version

#7478 {AKS} add --sku to az aks create/update command
  src/aks-preview/HISTORY.rst
  src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/agentpool_decorator.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_automatic_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign, auto-cal-version

#7452 [AKS] Add Node Initialization Taints preview CLI
  src/aks-preview/HISTORY.rst
  src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/agentpool_decorator.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_cluster_with_taints.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
Labels: AKS, Auto-Assign, auto-cal-version

#7479 [AKS] Add a new command to enable bootstrap artifact source when creating cluster
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_artifact_source.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign, auto-cal-version

#7481 {Service Connector}fix no attribute error
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign, auto-cal-version

#7488 [CI] Adjust tag operations in release suggestion
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#7482 {CI} Change version cal trigger condition
  .github/workflows/VersionCalPRComment.yml
Labels: CI, Auto-Assign

#7491 {AKS} Add required custom feature headers that automatic cluster needs to improve the recording success rate
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_automatic_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7493 {AKS} remove recording test for get-os-options
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_get_os_options.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7486 Release AKSArc CLI 1.1.2 .
  src/index.json
Labels: Auto-Assign, auto-cal-version

#7498 {CI} Use OIDC to trigger extension release pipeline
  .github/workflows/TriggerExtensionRelease.yml
Labels: CI, Auto-Assign

#7501 Arc Appliance CLI 1.1.0 April Release
  src/index.json
Labels: Auto-Assign

#7390 [k8s-runtime] Fix `TypeError: 'NoneType' object is not callable` error when deleting storage class
  src/k8s-runtime/HISTORY.rst
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/bgp_peer/_delete.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/load_balancer/_delete.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/service/_create.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_create.py
  src/k8s-runtime/azext_k8s_runtime/aaz/latest/k8s_runtime/storage_class/_delete.py
  src/k8s-runtime/azext_k8s_runtime/azext_metadata.json
  src/k8s-runtime/azext_k8s_runtime/tests/latest/recordings/test_load_balancer_enable_disable.yaml
  src/k8s-runtime/azext_k8s_runtime/tests/latest/recordings/test_storage_class_enable_disable.yaml
  src/k8s-runtime/azext_k8s_runtime/tests/latest/test_k8s_runtime.py
  src/k8s-runtime/setup.py
Labels: auto-cal-version

#7484 Managednetworkfabric Cli extension release 6.0.0
  src/managednetworkfabric/HISTORY.rst
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/device/__init__.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/device/_run_rw.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/internetgateway/_list.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/internetgateway/_show.py
  src/managednetworkfabric/azext_managednetworkfabric/aaz/latest/networkfabric/internetgateway/_update.py
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/config.ini
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/recordings/test_GA_Device_Rw_scenario1.yaml
  src/managednetworkfabric/azext_managednetworkfabric/tests/latest/test_device_rw.py
  src/managednetworkfabric/setup.py
Labels: auto-cal-version, major

#7507 [IoT] Adds IoT Operations extension v0.4.0b4
  src/index.json
Labels: IoT/CLI, Auto-Assign

#7497 [quantum] Assign "Storage account contributor" role to workspace for linked StorageAccount
  src/quantum/HISTORY.rst
  src/quantum/azext_quantum/__init__.py
  src/quantum/azext_quantum/operations/templates/create-workspace-and-assign-role.json
  src/quantum/setup.py
Labels: Quantum, Auto-Assign

#7487 [az fleet] remove preview markings for fleet hub-related parameters
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/_params.py
  src/fleet/setup.py
Labels: Auto-Assign, auto-cal-version

#7445 Adding new extension edgezones. new resource provider microsoft.edgezones version 2024-04-01-preview
  src/edgezones/HISTORY.rst
  src/edgezones/README.md
  src/edgezones/azext_edgezones/__init__.py
  src/edgezones/azext_edgezones/_help.py
  src/edgezones/azext_edgezones/_params.py
  src/edgezones/azext_edgezones/aaz/__init__.py
  src/edgezones/azext_edgezones/aaz/latest/__init__.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/__cmd_group.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/__init__.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/extended_zone/__cmd_group.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/extended_zone/__init__.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/extended_zone/_list.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/extended_zone/_register.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/extended_zone/_show.py
  src/edgezones/azext_edgezones/aaz/latest/edge_zones/extended_zone/_unregister.py
  src/edgezones/azext_edgezones/azext_metadata.json
  src/edgezones/azext_edgezones/commands.py
  src/edgezones/azext_edgezones/custom.py
  src/edgezones/azext_edgezones/tests/__init__.py
  src/edgezones/azext_edgezones/tests/latest/__init__.py
  src/edgezones/azext_edgezones/tests/latest/recordings/test_list_extended_zones.yaml
  src/edgezones/azext_edgezones/tests/latest/recordings/test_register_extended_zone.yaml
  src/edgezones/azext_edgezones/tests/latest/recordings/test_show_extended_zone.yaml
  src/edgezones/azext_edgezones/tests/latest/recordings/test_unregister_extended_zone.yaml
  src/edgezones/azext_edgezones/tests/latest/test_edgezones.py
  src/edgezones/setup.cfg
  src/edgezones/setup.py
  src/service_name.json
Labels: auto-cal-version, preview

#7490 [dataprotection] Support for PostgreSQLFlexibleServer and MySQL and code cleanup
  linter_exclusions.yml
  src/dataprotection/HISTORY.rst
  src/dataprotection/azext_dataprotection/azext_metadata.json
  src/dataprotection/azext_dataprotection/manual/Manifests/AzureDatabaseForMySQL.py
  src/dataprotection/azext_dataprotection/manual/Manifests/AzureDatabaseForPostgreSQLFlexibleServer.py
  src/dataprotection/azext_dataprotection/manual/Manifests/AzureKubernetesService.py
  src/dataprotection/azext_dataprotection/manual/Manifests/config.py
  src/dataprotection/azext_dataprotection/manual/_params.py
  src/dataprotection/azext_dataprotection/manual/commands.py
  src/dataprotection/azext_dataprotection/manual/custom.py
  src/dataprotection/azext_dataprotection/manual/helpers.py
  src/dataprotection/azext_dataprotection/tests/latest/recordings/test_dataprotection_backup_and_restore_mysql.yaml
  src/dataprotection/azext_dataprotection/tests/latest/recordings/test_dataprotection_backup_and_restore_pgflex.yaml
  src/dataprotection/azext_dataprotection/tests/latest/test_dataprotection_backup_and_restore_workloads.py
  src/dataprotection/setup.py
Labels: Data Protection, Auto-Assign, auto-cal-version, stable

#7517 [CI] Config pr and issue assignee
  .github/policies/resourceManagement.yml
Labels: CI, Auto-Assign

#7521 [ML] Release Extension 2.25.1
  src/index.json
Labels: extension/ml, Machine Learning, Auto-Assign

#7519 [AKS] Add a new command to enable bootstrap artifact source when updating cluster
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_artifact_source.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7458 AKS: Fix the roles to be included for Elastic SAN before installing Azure Container Storage
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign, auto-cal-version

#7535 [devcenter] Handle JSON error in "az devcenter dev environment show-logs-by-operation"
  src/devcenter/HISTORY.rst
  src/devcenter/azext_devcenter/action.py
  src/devcenter/azext_devcenter/custom.py
  src/devcenter/azext_devcenter/tests/latest/recordings/test_attached_network_scenario.yaml
  src/devcenter/azext_devcenter/tests/latest/recordings/test_dev_box_dataplane_scenario.yaml
  src/devcenter/azext_devcenter/tests/latest/recordings/test_dev_box_repair_dataplane_scenario.yaml
  src/devcenter/azext_devcenter/tests/latest/recordings/test_gallery_scenario.yaml
  src/devcenter/azext_devcenter/tests/latest/recordings/test_network_connection_scenario.yaml
  src/devcenter/azext_devcenter/tests/latest/recordings/test_pool_dataplane_scenario.yaml
  src/devcenter/azext_devcenter/tests/latest/recordings/test_pool_scenario.yaml
  src/devcenter/setup.py
Labels: Auto-Assign

#7418 TrustedSigning: CLI extension commands
  src/service_name.json
  src/trustedsigning/HISTORY.rst
  src/trustedsigning/README.md
  src/trustedsigning/azext_trustedsigning/__init__.py
  src/trustedsigning/azext_trustedsigning/_help.py
  src/trustedsigning/azext_trustedsigning/_params.py
  src/trustedsigning/azext_trustedsigning/aaz/__init__.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/__init__.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/__cmd_group.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/__init__.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_check_name_availability.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_create.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_delete.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_list.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_show.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_update.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/_wait.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/__cmd_group.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/__init__.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/_create.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/_delete.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/_list.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/_show.py
  src/trustedsigning/azext_trustedsigning/aaz/latest/trustedsigning/certificate_profile/_wait.py
  src/trustedsigning/azext_trustedsigning/azext_metadata.json
  src/trustedsigning/azext_trustedsigning/commands.py
  src/trustedsigning/azext_trustedsigning/custom.py
  src/trustedsigning/azext_trustedsigning/tests/__init__.py
  src/trustedsigning/azext_trustedsigning/tests/latest/__init__.py
  src/trustedsigning/azext_trustedsigning/tests/latest/recordings/test_trustedsigning_account.yaml
  src/trustedsigning/azext_trustedsigning/tests/latest/test_trustedsigning.py
  src/trustedsigning/setup.cfg
  src/trustedsigning/setup.py
Labels: do-not-merge, auto-cal-version

#7430 Create Standby pool cli
  src/service_name.json
  src/standbypool/HISTORY.rst
  src/standbypool/README.md
  src/standbypool/azext_standbypool/__init__.py
  src/standbypool/azext_standbypool/_help.py
  src/standbypool/azext_standbypool/_params.py
  src/standbypool/azext_standbypool/aaz/__init__.py
  src/standbypool/azext_standbypool/aaz/latest/__init__.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/__cmd_group.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/__init__.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_create.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_delete.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_list.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_show.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_update.py
  src/standbypool/azext_standbypool/aaz/latest/standby_container_group_pool/_wait.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/__cmd_group.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/__init__.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_create.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_delete.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_list.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_show.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_update.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/_wait.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/vm/__cmd_group.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/vm/__init__.py
  src/standbypool/azext_standbypool/aaz/latest/standby_vm_pool/vm/_list.py
  src/standbypool/azext_standbypool/azext_metadata.json
  src/standbypool/azext_standbypool/commands.py
  src/standbypool/azext_standbypool/custom.py
  src/standbypool/azext_standbypool/tests/__init__.py
  src/standbypool/azext_standbypool/tests/latest/CreateContainerGroupProfileTemplate.json
  src/standbypool/azext_standbypool/tests/latest/__init__.py
  src/standbypool/azext_standbypool/tests/latest/recordings/test_standby_container_group_pool_scenarios.yaml
  src/standbypool/azext_standbypool/tests/latest/recordings/test_standby_virtual_machine_pool_scenarios.yaml
  src/standbypool/azext_standbypool/tests/latest/test_standbypool.py
  src/standbypool/setup.cfg
  src/standbypool/setup.py
Labels: auto-cal-version

#7357 [Serial Console] Fix for unit tests, new authentication flow preparation
  src/serial-console/HISTORY.rst
  src/serial-console/azext_serialconsole/custom.py
  src/serial-console/azext_serialconsole/tests/latest/__init__.py
  src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VM.yaml
  src/serial-console/azext_serialconsole/tests/latest/recordings/test_check_resource_VMSS.yaml
  src/serial-console/azext_serialconsole/tests/latest/recordings/test_enable_disable.yaml
  src/serial-console/azext_serialconsole/tests/latest/test_serialconsole_scenario.py
  src/serial-console/setup.py
Labels: customer-reported

#7405 Connectedvmware v1.0.1
  src/connectedvmware/HISTORY.rst
  src/connectedvmware/azext_connectedvmware/_help.py
  src/connectedvmware/azext_connectedvmware/_params.py
  src/connectedvmware/azext_connectedvmware/azext_metadata.json
  src/connectedvmware/azext_connectedvmware/custom.py
  src/connectedvmware/setup.py
Labels: Auto-Assign, auto-cal-version

#7514 [AKS] Add `--enable-azure-monitor-app-monitoring` and `--disable-azure-monitor-app-monitoring` to aks-preview
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_azuremonitorappmonitoring.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_azuremonitorappmonitoring.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7548 {AKS} Correct the property `disable_outbound_nat` in `windows_profile` and add UT
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/agentpool_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_agentpool_decorator.py
Labels: AKS, Auto-Assign

#7508 [AKS] support `--yes` for `az aks mesh upgrade` commands.
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_azure_service_mesh_canary_upgrade.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7546 {AKS} az aks create/update: ignore invalid ip error in ip_ranges validator
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/tests/latest/test_validators.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7549 {AKS} Support to enable azure container insight monitoring when the sku name is automatic
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_automatic_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#7544 [AKS] Add option WindowsAnnual to --os-sku for az aks nodepool add
  src/aks-preview/HISTORY.rst
  src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_nodepool_add_with_ossku_windowsannual.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7142 Fix azdev style issues for bastion
  src/bastion/azext_bastion/custom.py
  src/bastion/azext_bastion/tests/latest/recordings/test_bastion_host_crud.yaml
Labels: customer-reported, Network, Auto-Assign

#7471 [Spring] Private Storage Access support
  src/spring/HISTORY.md
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/custom.py
  src/spring/azext_spring/spring_instance.py
  src/spring/azext_spring/tests/latest/test_asa_create.py
  src/spring/azext_spring/tests/latest/test_asa_update.py
Labels: Auto-Assign, auto-cal-version

#7554 {AKS} Fix several test cases broken by API version bump in network module
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_and_update_with_http_proxy_config.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_pod_ip_allocation_mode_static_block.yaml
Labels: AKS, Network, Auto-Assign

#7531 [AKS-preview] az aks upgrade: Add forceupgrade settings to aks preview cli
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_upgrade_upgrade_settings.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7551 `az containerapp up`: Fix InvalidResourceType error when cloud is not AzureCloud
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/_up_utils.py
  src/containerapp/azext_containerapp/_utils.py
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_up_mooncake.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py
Labels: Auto-Assign, ContainerApp

#7525 [Spring] Add new params for custom actuator
  src/spring/HISTORY.md
  src/spring/azext_spring/_deployment_factory.py
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/_utils.py
  src/spring/azext_spring/_validators_enterprise.py
  src/spring/azext_spring/app.py
  src/spring/azext_spring/tests/latest/recordings/test_app_actuator_configs.yaml
  src/spring/azext_spring/tests/latest/test_asa_app.py
  src/spring/azext_spring/tests/latest/test_asa_app_scenario.py
  src/spring/setup.py
Labels: Auto-Assign

#7444 [Spring] Show ACS revision (include commit id)
  src/spring/HISTORY.md
  src/spring/azext_spring/application_configuration_service.py
  src/spring/azext_spring/tests/latest/test_asa_application_configuration_service.py
  src/spring/setup.py
Labels: AKS, Auto-Assign, auto-cal-version

#7561 Arc Appliance CLI 1.1.1 May Release
  src/index.json
Labels: Auto-Assign

#7512 [AKS]: Fix Scenario test failure for Azure Container Storage
  src/aks-preview/azext_aks_preview/azurecontainerstorage/acstor_ops.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
Labels: AKS, Auto-Assign

#7557 {AKS} Support to enable azure monitor profile when the sku name is automatic
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_automatic_sku.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign
