Repository Azure/azure-cli-extensions, pull requests merged in 2024-12, with the labels that each got.

#8331 {internet-analyzer} Fix disallowed html tag
  src/internet-analyzer/azext_internet_analyzer/_params.py
Labels: Auto-Assign, Internet Analyzer

#8326 {alertsmanagement} Fix disawllowed html tag
  src/alertsmanagement/azext_alertsmanagement/_help.py
  src/alertsmanagement/azext_alertsmanagement/_params.py
Labels: Alerts Management, Auto-Assign

#8332 {serviceconnector-passwordless} Fix disallowed html tag
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_help.py
Labels: Auto-Assign

#8306 {spring-cloud} Fix disallowed html tag
  src/spring-cloud/azext_spring_cloud/_help.py
  src/spring-cloud/azext_spring_cloud/_params.py
  src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_persistent_storage.yaml
  src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_stop_and_start_service.yaml
Labels: Spring Cloud, Auto-Assign

#8328 {connectedvmware} Fix html tag lint
  src/connectedvmware/azext_connectedvmware/_params.py
Labels: Auto-Assign

#8336 {devcenter } Fix disallowed html tag
  src/devcenter/azext_devcenter/_params.py
Labels: Auto-Assign

#8341 {datamigration} Fix disallowed html tag
  src/datamigration/azext_datamigration/manual/_params.py
Labels: Data Migration, Auto-Assign

#8360 {githooks} Improve pre-commit message
  .githooks/pre-commit.ps1
  .githooks/pre-commit.sh
Labels: do-not-merge

#8329 {containerapp} Fix disallowed html tags
  src/containerapp/azext_containerapp/_params.py
Labels: Auto-Assign, ContainerApp

#8367 {CI} Optimize azure-cli-extensions githook
  .githooks/pre-push.ps1
  .githooks/pre-push.sh
Labels: CI, Auto-Assign

#8361 NetworkCloud : 2024-07-01 API : Redact userdata and networkdata in aaz test recordings.
  src/networkcloud/azext_networkcloud/tests/latest/recordings/test_virtualmachine_scenario1.yaml
Labels: do-not-merge

#8387 [load] add project structure to README
  src/load/README.md
Labels: do-not-merge
