Repository Azure/azure-cli-extensions, pull requests merged in 2025-03, with the labels that each got.

#8502 Changing the schema migration package download link
  src/datamigration/HISTORY.rst
  src/datamigration/azext_datamigration/manual/helper.py
  src/datamigration/setup.py
Labels: customer-reported

#8528 {CI} Update GitHub workflows to use ubuntu-latest
  .github/workflows/AddIssueComment.yml
  .github/workflows/AddIssueCommentWithLabel.yml
Labels: CI, Auto-Assign

#8318 UDR version update in virtual-network-manager extension
  src/network-manager/HISTORY.rst
  src/network-manager/azext_network_manager/aaz/latest/network/manager/_post_commit.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/_create.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/_delete.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/_list.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/_show.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/_update.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/_wait.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/_create.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/_delete.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/_list.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/_show.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/_update.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/_wait.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/rule/_create.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/rule/_delete.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/rule/_list.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/rule/_show.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/rule/_update.py
  src/network-manager/azext_network_manager/aaz/latest/network/manager/routing_config/rule_collection/rule/_wait.py
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_admin_rule_collection_crud.yaml
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_admin_rule_crud.yaml
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_connect_config_crud.yaml
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_list_queries.yaml
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_routing_config_crud.yaml
  src/network-manager/azext_network_manager/tests/latest/recordings/test_network_manager_static_member_crud.yaml
  src/network-manager/azext_network_manager/tests/latest/test_network_scenario.py
  src/network-manager/setup.py
Labels: Network, Auto-Assign

#8486 Add non-premium disk option for repair VM
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/_help.py
  src/vm-repair/azext_vm_repair/_params.py
  src/vm-repair/azext_vm_repair/custom.py
  src/vm-repair/azext_vm_repair/tests/latest/test_repair_commands.py
  src/vm-repair/setup.py
Labels: Compute, Auto-Assign

#8533 {CosmosDB} `az cosmosdb restore`: Skip client side restore validation, which causes timeouts for large restore
  src/cosmosdb-preview/HISTORY.rst
  src/cosmosdb-preview/azext_cosmosdb_preview/custom.py
  src/cosmosdb-preview/setup.py
Labels: customer-reported, CosmosDB, Auto-Assign

#8547 [Quantum] Redact SAS token signatures in CLI extension test recordings
  src/quantum/azext_quantum/tests/latest/recordings/test_submit.yaml
Labels: Quantum, Auto-Assign

#8549 [Quantum] Quantum CLI Extension Release, Version 1.0.0b5
  src/quantum/HISTORY.rst
  src/quantum/azext_quantum/__init__.py
  src/quantum/setup.py
Labels: Quantum, Auto-Assign

#8384 Remove version import in module setup
  src/ad/setup.py
  src/alias/setup.py
  src/attestation/setup.py
  src/automation/setup.py
  src/cloudservice/setup.py
  src/communication/setup.py
  src/confidentialledger/setup.py
  src/connectedmachine/setup.py
  src/datadog/setup.py
  src/datafactory/setup.py
  src/datamigration/setup.py
  src/datashare/setup.py
  src/devcenter/setup.py
  src/diskpool/setup.py
  src/dns-resolver/setup.py
  src/edgeorder/setup.py
  src/elastic/setup.py
  src/footprint/setup.py
  src/guestconfig/setup.py
  src/hardware-security-modules/setup.py
  src/healthbot/setup.py
  src/healthcareapis/setup.py
  src/interactive/setup.py
  src/kusto/setup.py
  src/logz/setup.py
  src/maintenance/setup.py
  src/offazure/setup.py
  src/purview/setup.py
  src/quota/setup.py
  src/resource-mover/setup.py
  src/serviceconnector-passwordless/setup.py
  src/stack-hci/setup.py
  src/stream-analytics/setup.py
  src/swiftlet/setup.py
  src/timeseriesinsights/setup.py
Labels: skip-cal-version

#8557 {CI} Move find_extension_upgraded.py to azure-cli-extensions repo
  scripts/ci/find_extension_upgraded.py
Labels: CI, Auto-Assign

#8538 [Spring] Add migration command from Azure Spring Apps to Azure Container Apps
  src/spring/HISTORY.md
  src/spring/azext_spring/_help.py
  src/spring/azext_spring/_params.py
  src/spring/azext_spring/commands.py
  src/spring/azext_spring/migration/__init__.py
  src/spring/azext_spring/migration/converter/__init__.py
  src/spring/azext_spring/migration/converter/acs_converter.py
  src/spring/azext_spring/migration/converter/app_converter.py
  src/spring/azext_spring/migration/converter/base_converter.py
  src/spring/azext_spring/migration/converter/cert_converter.py
  src/spring/azext_spring/migration/converter/config_server_converter.py
  src/spring/azext_spring/migration/converter/conversion_context.py
  src/spring/azext_spring/migration/converter/environment_converter.py
  src/spring/azext_spring/migration/converter/eureka_converter.py
  src/spring/azext_spring/migration/converter/gateway_converter.py
  src/spring/azext_spring/migration/converter/live_view_converter.py
  src/spring/azext_spring/migration/converter/main_converter.py
  src/spring/azext_spring/migration/converter/param_converter.py
  src/spring/azext_spring/migration/converter/readme_converter.py
  src/spring/azext_spring/migration/converter/service_registry_converter.py
  src/spring/azext_spring/migration/converter/templates/app.bicep.j2
  src/spring/azext_spring/migration/converter/templates/cert.bicep.j2
  src/spring/azext_spring/migration/converter/templates/config_server.bicep.j2
  src/spring/azext_spring/migration/converter/templates/environment.bicep.j2
  src/spring/azext_spring/migration/converter/templates/eureka.bicep.j2
  src/spring/azext_spring/migration/converter/templates/gateway.bicep.j2
  src/spring/azext_spring/migration/converter/templates/main.bicep.j2
  src/spring/azext_spring/migration/converter/templates/param.bicepparam.j2
  src/spring/azext_spring/migration/converter/templates/readme.md.j2
  src/spring/azext_spring/migration/converter/templates/spring_boot_admin.bicep.j2
  src/spring/azext_spring/migration/migration_operations.py
  src/spring/azext_spring/spring_instance.py
  src/spring/azext_spring/tests/latest/recordings/test_asa_export.yaml
  src/spring/azext_spring/tests/latest/recordings/test_persistent_storage.yaml
  src/spring/azext_spring/tests/latest/test_asa_export.py
  src/spring/setup.py
Labels: Auto-Assign, ContainerApp

#8543 {CI} Update Azure Pipelines to use Ubuntu 22.04 pools
  .azure-pipelines/sync-alias.yml
  .azure-pipelines/templates/variables.yml
  azure-pipelines.yml
Labels: CI, Auto-Assign

#8562 [Quantum] Roll back the quantum extension version number to 1.0.0b4
  src/quantum/azext_quantum/__init__.py
  src/quantum/setup.py
Labels: Quantum, Auto-Assign, skip-cal-version

#8560 [k8s-extension] Update extension CLI to v1.6.4
  src/k8s-extension/HISTORY.rst
  src/k8s-extension/azext_k8s_extension/partner_extensions/DataProtectionKubernetes.py
  src/k8s-extension/azext_k8s_extension/partner_extensions/azuremonitormetrics/deaults.py
  src/k8s-extension/setup.py
Labels: Auto-Assign

#8567 {Ip-group} Release a new package
  src/ip-group/HISTORY.rst
  src/ip-group/setup.py
Labels: skip-cal-version

#8516 {serviceconnector-passwordless} Fix Fabric Auth Endpoint URL
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#8566 [Containerapp] Release version 1.1.0b4
  src/containerapp/HISTORY.rst
  src/containerapp/azext_containerapp/commands.py
  src/containerapp/azext_containerapp/tests/latest/recordings/test_container_app_mount_azurefile_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_container_app_mount_nfsazurefile_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_http_route_config_crudoperations_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_env_logs_e2e.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerapp_preview_connected_env_storage.yaml
  src/containerapp/azext_containerapp/tests/latest/recordings/test_containerappjob_create_with_yaml.yaml
  src/containerapp/azext_containerapp/tests/latest/test_containerapp_env_http_route_config.py
  src/containerapp/setup.py
Labels: Auto-Assign, ContainerApp

#8564 [Quantum] Bug fix for retracted Quantum CLI extension v1.0.0b5 release
  src/quantum/azext_quantum/vendored_sdks/azure_quantum_python/__init__.py
Labels: Quantum, Auto-Assign

#8575 [Quantum] Quantum CLI Extension Release, Version 1.0.0b6
  src/quantum/HISTORY.rst
  src/quantum/azext_quantum/__init__.py
  src/quantum/setup.py
Labels: Quantum, Auto-Assign, skip-cal-version

#8573 {CI} Update sync-alias.yml to push branch to azclibot/azure-cli-extensions repo
  .azure-pipelines/sync-alias.yml
Labels: CI, Auto-Assign

#8577 Modify dft tests to use qcschema instead of xyz.
  src/quantum/azext_quantum/tests/latest/input_data/dft_molecule_failure_bad_params.json
  src/quantum/azext_quantum/tests/latest/input_data/dft_molecule_failure_no_convergence.json
  src/quantum/azext_quantum/tests/latest/input_data/dft_molecule_success.json
  src/quantum/azext_quantum/tests/latest/test_quantum_jobs.py
Labels: customer-reported, Quantum, Auto-Assign

#8398 [connectedmachine] update list command
  src/connectedmachine/HISTORY.rst
  src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_list.py
  src/connectedmachine/azext_connectedmachine/tests/latest/recordings/test_machine_and_extension.yaml
  src/connectedmachine/azext_connectedmachine/tests/latest/recordings/test_private_link.yaml
  src/connectedmachine/azext_connectedmachine/tests/latest/test_ConnectedMachineAndExtension_scenario.py
  src/connectedmachine/setup.py
Labels: Auto-Assign, skip-cal-version

#8559 az k8s-configuration Release 2.2.0
  src/k8s-configuration/HISTORY.rst
  src/k8s-configuration/azext_k8s_configuration/_client_factory.py
  src/k8s-configuration/azext_k8s_configuration/_params.py
  src/k8s-configuration/azext_k8s_configuration/consts.py
  src/k8s-configuration/azext_k8s_configuration/providers/FluxConfigurationProvider.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/_flux_configuration_client.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/models.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/_configuration.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/_flux_configuration_client.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/_serialization.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/_version.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/_configuration.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/_flux_configuration_client.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/operations/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/operations/_flux_config_operation_status_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/operations/_flux_configurations_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/aio/operations/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/models/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/models/_flux_configuration_client_enums.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/models/_models_py3.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/models/_patch.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/operations/__init__.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/operations/_flux_config_operation_status_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/operations/_flux_configurations_operations.py
  src/k8s-configuration/azext_k8s_configuration/vendored_sdks/v2024_11_01/operations/_patch.py
  src/k8s-configuration/setup.py
Labels: Auto-Assign

#8524 Add Istio egress CLI commands
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/_validators.py
  src/aks-preview/azext_aks_preview/azurecontainerstorage/_helpers.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#8606 {aks-preview} Add codeql exclusion for aks-preview
  CodeQL.yml
Labels: AKS, Auto-Assign

#8602 {internet-analyzer} Patch version for updated doc
  src/internet-analyzer/HISTORY.rst
  src/internet-analyzer/setup.py
Labels: Auto-Assign, Internet Analyzer

#8609 [Spring] Support BYOC in migration command
  src/spring/HISTORY.md
  src/spring/azext_spring/migration/converter/app_converter.py
  src/spring/azext_spring/migration/converter/base_converter.py
  src/spring/azext_spring/migration/converter/cert_converter.py
  src/spring/azext_spring/migration/converter/environment_converter.py
  src/spring/azext_spring/migration/converter/main_converter.py
  src/spring/azext_spring/migration/converter/param_converter.py
  src/spring/azext_spring/migration/converter/readme_converter.py
  src/spring/azext_spring/migration/converter/templates/app.bicep.j2
  src/spring/azext_spring/migration/converter/templates/config_server.bicep.j2
  src/spring/azext_spring/migration/converter/templates/environment.bicep.j2
  src/spring/azext_spring/migration/converter/templates/main.bicep.j2
  src/spring/azext_spring/migration/converter/templates/param.bicepparam.j2
  src/spring/azext_spring/migration/converter/templates/readme.md.j2
  src/spring/setup.py
Labels: Auto-Assign

#8607 {spring-cloud} Patch version for updated doc
  src/spring-cloud/HISTORY.md
  src/spring-cloud/azext_spring_cloud/tests/latest/recordings/test_persistent_storage.yaml
  src/spring-cloud/setup.py
Labels: Spring Cloud, Auto-Assign

#8610 {CI} Adjust version calculation to use `whl` for base metadata
  .github/workflows/VersionCalPRComment.yml
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign
