Repository Azure/azure-cli-extensions, pull requests merged in 2025-04, with the labels that each got.

#8628 {Image-copy} `az image copy`: Set minimum TLS version to 1.2 when creating temporary storage account
  src/image-copy/HISTORY.rst
  src/image-copy/azext_imagecopy/create_target.py
  src/image-copy/azext_imagecopy/tests/latest/recordings/test_image_copy.yaml
  src/image-copy/setup.py
Labels: Compute, Auto-Assign

#8638 [Spring] [CodeQL] Use sha256 instead of md5
  src/spring/azext_spring/migration/converter/base_converter.py
Labels: Auto-Assign

#8627 {CI} Add `azdev style&linter` into github workflow
  .github/actions/env-setup/action.yml
  .github/workflows/AzdevLinter.yml
  .github/workflows/AzdevStyle.yml
Labels: CI, Auto-Assign

#8642 {CI} Reset workflow for no changed module prs
  .github/workflows/AzdevLinter.yml
  .github/workflows/AzdevStyle.yml
Labels: CI, Auto-Assign

#8617 {AKS} Rename to addon-autoscaling preview CLI to optimized-addon-scaling
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_optimized_addon_scaling.yaml
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_update_with_optimized_addon_scaling.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign, major

#8651 {CI} Add linter example validate rule
  .github/actions/env-setup/action.yml
  .github/workflows/AzdevLinter.yml
  .github/workflows/AzdevStyle.yml
Labels: CI, Auto-Assign

#8636 Update CLI to create role assignment
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/_client_factory.py
  src/fleet/azext_fleet/_helpers.py
  src/fleet/azext_fleet/constants.py
  src/fleet/azext_fleet/custom.py
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubful.yaml
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubless.yaml
  src/fleet/setup.py
Labels: Auto-Assign

#8662 {CI} Fix version cal for initial module
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#8663 {CI} Fix issue when `isPreview: false`
  scripts/ci/release_version_cal.py
Labels: CI, Auto-Assign

#8666 Making delegated-subnet-id optional and adding the missing --private-endpoint-ip-address param for MI cassandra data center
  src/cosmosdb-preview/HISTORY.rst
  src/cosmosdb-preview/azext_cosmosdb_preview/_params.py
  src/cosmosdb-preview/azext_cosmosdb_preview/custom.py
  src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/recordings/test_managed_cassandra_cluster_create_with_azure_connection_method.yaml
  src/cosmosdb-preview/azext_cosmosdb_preview/tests/latest/test_cosmosdb-cassandrami_scenario.py
  src/cosmosdb-preview/setup.py
Labels: customer-reported

#8620 Updating linux image selection
  src/vm-repair/HISTORY.rst
  src/vm-repair/azext_vm_repair/custom.py
  src/vm-repair/azext_vm_repair/repair_utils.py
  src/vm-repair/setup.py
Labels: Compute, Auto-Assign

#8664 [AMG] Support multi-subscription scenario for AMW integration
  src/amg/HISTORY.rst
  src/amg/azext_amg/_help.py
  src/amg/azext_amg/_params.py
  src/amg/azext_amg/commands.py
  src/amg/azext_amg/custom.py
  src/amg/azext_amg/integrations.py
  src/amg/azext_amg/tests/latest/recordings/test_amg_api_key_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_backup_restore.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_crud.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_integrations_monitor.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_migrate_dry_run.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_migrate_override.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_migrate_remapping.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_migrate_simple_e2e.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_private_endpoint.yaml
  src/amg/azext_amg/tests/latest/recordings/test_amg_service_account_e2e.yaml
  src/amg/azext_amg/tests/latest/test_amg_migrate_scenario.py
  src/amg/azext_amg/tests/latest/test_amg_scenario.py
  src/amg/azext_amg/tests/latest/test_definitions.py
  src/amg/setup.py
Labels: extension/grafana, Auto-Assign

#8571 Added breaking change announcement for az ssh arc commands
  src/ssh/azext_ssh/_breaking_change.py
Labels: customer-reported, VM SSH, Auto-Assign

#8684 Fix Private Fleet Bug
  src/fleet/HISTORY.rst
  src/fleet/azext_fleet/custom.py
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubful.yaml
  src/fleet/azext_fleet/tests/latest/recordings/test_fleet_hubless.yaml
  src/fleet/setup.py
Labels: Auto-Assign

#8569 feat: Support az aks loadbalancer commands
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_client_factory.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/commands.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/loadbalancerconfiguration.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_loadbalancer_commands.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_loadbalancer_configuration.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#8688 {serviceconnector-passwordless} Add docs link for Fabric SQL Database Manual Steps
  src/serviceconnector-passwordless/HISTORY.rst
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py
  src/serviceconnector-passwordless/azext_serviceconnector_passwordless/config.py
  src/serviceconnector-passwordless/setup.py
Labels: Auto-Assign

#8698 {AKS} Fix live test pipeline
  src/aks-preview/azcli_aks_live_test/scripts/setup_venv.sh
  src/aks-preview/azcli_aks_live_test/scripts/test_cli_live.sh
  src/aks-preview/azcli_aks_live_test/scripts/test_ext_live.sh
Labels: AKS, Auto-Assign

#8703 {AKS} Fix issue #31345: Re-generate the SDK for API version 2025-02-02-preview with @autorest/python@6.32.3
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_container_service_client.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_serialization.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_utils/__init__.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/_version.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/_container_service_client.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/_metadata.json
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/_utils/__init__.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/_utils/serialization.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/_container_service_client.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_agent_pools_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_container_service_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_load_balancers_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_machines_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_maintenance_configurations_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_managed_cluster_snapshots_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_managed_clusters_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_namespaces_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_operation_status_result_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_private_endpoint_connections_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_private_link_resources_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_resolve_private_link_service_id_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_snapshots_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_trusted_access_role_bindings_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/aio/operations/_trusted_access_roles_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/models/_models_py3.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_agent_pools_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_container_service_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_load_balancers_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_machines_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_maintenance_configurations_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_managed_cluster_snapshots_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_managed_clusters_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_namespaces_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_operation_status_result_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_private_endpoint_connections_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_private_link_resources_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_resolve_private_link_service_id_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_snapshots_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_trusted_access_role_bindings_operations.py
  src/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2025_02_02_preview/operations/_trusted_access_roles_operations.py
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#8687 feat(acns) add advanced network policies options for az create and update commands
  src/aks-preview/HISTORY.rst
  src/aks-preview/azext_aks_preview/_consts.py
  src/aks-preview/azext_aks_preview/_help.py
  src/aks-preview/azext_aks_preview/_params.py
  src/aks-preview/azext_aks_preview/custom.py
  src/aks-preview/azext_aks_preview/managed_cluster_decorator.py
  src/aks-preview/azext_aks_preview/tests/latest/recordings/test_aks_create_with_advanced_networkpolicies.yaml
  src/aks-preview/azext_aks_preview/tests/latest/test_aks_commands.py
  src/aks-preview/azext_aks_preview/tests/latest/test_managed_cluster_decorator.py
  src/aks-preview/linter_exclusions.yml
  src/aks-preview/setup.py
Labels: AKS, Auto-Assign

#8707 fix: update release note for aks-preview 14.0.0b6
  src/aks-preview/HISTORY.rst
Labels: AKS, Auto-Assign
